package com.ballydev.sds.jackpot.keypad;

/**
 * Contains Constants specific to keypad process.
 * 
 * @author ranjithkumarm
 * 
 */
public interface IKeypadProcessConstants {	
	String JACKPOT_ENGINE_KEYPAD_NAME 				= "JACKPOT_ENGINE";
	// RESPONSE VALUES
	int SESSION_INIT_RESPONSE 						= 1;
	int SESSION_PRINTER_DETAILS_RESPONSE 			= 2;
	int SESSION_SLIP_PROCESS_RESPONSE 				= 3;
	// SIT CONFIG VALUES
	String PROMPT_KP_JP_PROCESS 					= "PROMPT.KP.JP.PROCESS";
	String PROMPT_KP_JP_AMOUNT 						= "PROMPT.KP.JP.AMOUNT";
	String PROMPT_KP_JP_PAYLINE 					= "PROMPT.KP.JP.PAYLINE";
	String PROMPT_KP_JP_WINCOM 						= "PROMPT.KP.JP.WINCOM";
	String PROMPT_KP_JP_COINS 						= "PROMPT.KP.JP.COINS";
	String PROMPT_KP_JP_SHIFT 						= "PROMPT.KP.JP.SHIFT";
	String PROMPT_KP_JP_POUCH_PAY 					= "PROMPT.KP.JP.POUCH.PAY";
	String PROMPT_KP_JP_EMP_AUTH 					= "PROMPT.KP.JP.EMP.AUTH";
	String KP_CLEAR_JACKPOT_FLAG 					= "PROMPT.KP.JP.CMHP";	
	String SITE_CASINO_NAME 						= "SITE.MASTER.SITE.SHRT.NAME";
	// EXTN DEFAULT CASINO NAME
	String PRINT_CASINO_NAME 						= "JACKPOT.PRINT.CASINO.NAME";
	// CURRENCY SYMBOL
	String SITE_CURRENCY_SYMBOL 					= "CURRENCY.SYMBOL";
	String CURRENCY_SYMBOL_DEFAULT 					= "$";// DEFAULT CURRENCY SYMBOL.
	// DATE FORMAT
	String SLIP_DATE_FORMAT 						= "dd-MMM-yy HH:mm";
	// SHIFT LABEL VALUES
	String DAY_SHIFT_LABEL 							= "JACKPOT.SHIFT.DAY";
	String SWING_SHIFT_LABEL 						= "JACKPOT.SHIFT.SWING";
	String GRAVEYARD_SHIFT_LABEL 					= "JACKPOT.SHIFT.GRAVEYARD";
	// SCHEMA FILE PATH
	String PRINTER_CMD_XML_FILE_PATH_KEYPAD 		= "/sds/props/jackpotengine/printercmd.xml";
	String SLIP_SCHEMA_XML_FILE_PATH_KEYPAD 		= "/sds/props/jackpotengine/slipschema.xml";
	// TEMP SITE NUMBER
	int TEMP_SITE_NUMBER 							= 1;
	String SITE_CONFIG_BOOLEAN_VALID 				= "YES";
	// EMPLOYEE JACKPOT FUNCTION
	String EMP_FUNCTION_PROCESS_PENDING_JP 			= "Jackpot - Process Pending Jackpot";
	String EMP_FUNCTION_AUTH_ONE_PERSON 			= "Jackpot - Jackpot One Person Auth";
	// JACKPOT SLIP PRINT TYPE
	String JACKPOT_PRINT_SLIP_TYPE 					= "JACKPOT";	
	String CHECK_PRINT_SLIP_TYPE 					= "CHECK";

	//String JACKPOT_ENGINE_EXT_LANGUAGE 				= "jp.lang.code";

	String JACKPOT_ENGINE_EXT_LANGUAGE_DEFAULT 		= "en_US";

	String JACKPOT_SLIP_SEQUENCE_NO_PREFIX 			= "J";

	int JACKPOT_SHIFT_DAY 						 	= 1;
	int JACKPOT_SHIFT_SWING 						= 2;
	int JACKPOT_SHIFT_GRAVEYARD 				 	= 3;

	String DEFAULT_JACKPOT_SHIFT_DAY 			 	= "Day";
	String DEFAULT_JACKPOT_SHIFT_SWING 			 	= "Swing";
	String DEFAULT_JACKPOT_SHIFT_GRAVEYARD 		 	= "Graveyard";

	String DEFAULT_JACKPOT_SHIFT_DAY_SHORT 		 	= "D";
	String DEFAULT_JACKPOT_SHIFT_SWING_SHORT 	 	= "S";
	String DEFAULT_JACKPOT_SHIFT_GRAVEYARD_SHORT 	= "G";

	String EPSON_PRINTER_SUBSTRING 				 	= "EPSON";
	String LASER_JET_PRINTER_SUBSTRING 			 	= "LaserJet";

	String SLOT_EXTERNALIZED_KEY 				 	= "JACKPOT.PRINT.ACNF.NUMBER";

	String SITE_PARAM_VALID_HPJP_AMOUNT 		 	= "HPJP.REQUIRES.VALID.HPJP.AMOUNT";
	String SITE_PARAM_PP_MAX_AMOUNT     			= "POUCH.PAY.JACKPOT.LIMIT";

	String ROLE_PARAM_AUTH_LVL_KEY 					= "AUTHORIZATION LEVEL";
	String ROLE_PARAM_AUTH_AMOUNT  					= "JACKPOT AMOUNT";

	int DEFAULT_SESSION_LENGTH_IN_MINS 				= 2;
	
	String SIGLE_SPACE  							= " ";
	String EMPTY_STRING 							= "";
	String NEW_LINE_FEED 							= " \r\n";
	String NEW_TAB_FEED 							= " \t";
	String UNDERLINE_CHAR 							= "_";
	
	// JACKPOT CHECK SLIP CONSTANTS FROM SCHEMA FILE	
	public String CHECK_PRINT_JACKPOT_SIGN 			= "CHECK.PRINT.JACKPOT.SIGN";			// Signature
	public String CHECK_PRINT_JACKPOT_ID_NO 		= "CHECK.PRINT.JACKPOT.ID.NO";			// ID NO
	public String CHECK_PRINT_JACKPOT_STAMP 		= "CHECK.PRINT.JACKPOT.STAMP";			// Stamp
	
	/* MULTI RANGE JACKPOT SIGNATURE LEVELS */	 
	 String ENABLE_JACKPOT_MULTI_RANGE_SIGN 		= "ENABLE.JP.MULTI.RANGE.SIGN"; 	 
	 String NO_OF_MULTI_RANGE_SIGN_LEVELS 			= "NO.OF.JP.MULTI.RANGE.SIGN";	 
	 String MULTI_RANGE_SIGN_1 						= "JP.MULTI.RANGE.SIGN.1";   //"5.00"; //"JP.MULTI.RANGE.SIGN.1";
	 String MULTI_RANGE_SIGN_2 						= "JP.MULTI.RANGE.SIGN.2";	//"100.00"; //"JP.MULTI.RANGE.SIGN.2";	 
	 String MULTI_RANGE_SIGN_3 						= "JP.MULTI.RANGE.SIGN.3";  //"500.00"; //"JP.MULTI.RANGE.SIGN.3";
	 String MULTI_RANGE_SIGN_4 						= "JP.MULTI.RANGE.SIGN.4";  //"1000.00"; //"JP.MULTI.RANGE.SIGN.4";
	 String MULTI_RANGE_SIGN_5 						= "JP.MULTI.RANGE.SIGN.5";  //"10000"; //"JP.MULTI.RANGE.SIGN.5";
	 
	 String ATTMPTS_FOR_JP_KEYPAD 					= "ATTMPTS.FOR.JP.KEYPAD";
	 String JP_KP_VALID_SESSION_LENGTH 				= "JP.KP.VALID.SESSION.LENGTH";
	 
	// SLIP PRINT FONT TYPE
	String SLIP_PRINT_FONT_BOLD 					= "courier-BOLD-10";
	String SLIP_PRINT_FONT_PLAIN 					= "courier-PLAIN-12";
	
	public String CHECK_PRINT_JACKPOT_VALID_DATE_STATIC = "CHECK.PRINT.JACKPOT.VALID.TILL.DATE.STATIC"; // JACKPOT SLIP VALID TILL  DATE OF ISSUE ONLY) 
	
	String NUM_AUTH_SIGNATURES_FOR_EXCESSIVE_VARIANCES = "NO.OF.AUTH.SIGN.FOR.EXCESSIVE.VAR";

	String JP_DOLLAR_VARIANCE_FOR_ADDITIONAL_AUTHORIZERS = "JPT.DOLL.VAR.FOR.ADDITIONAL.AUTH";

	String JP_PERCENT_VARIANCE_FOR_ADDITIONAL_AUTHORIZERS = "JPT.PER.VAR.FOR.ADDITIONAL.AUTH";
	
	String CURRENCY_SYMBOL = "CURRENCY.SYMBOL";

}
