package com.ballydev.sds.jackpot.keypad;

/**
 * Label Key Constants.
 * 
 * @author ranjithkumarm
 *
 */
public interface KeypadLabelKeyConstants {
	
		
	public  String  SLIPS_UI_BUTTON="GENERAL.TOUCHSCREEN.MENU.SLIPSUI";
	
	public  String  JACKPOT_UI_BUTTON="GENERAL.TOUCHSCREEN.MENU.JACKPOTUI";
	
	public  String  VOUCHER_UI_BUTTON="GENERAL.TOUCHSCREEN.MENU.VOUCHERUI";
	
	public  String  LOG_OUT_BUTTON="JACKPOT.BTN.LOGOUT";
	
	public  String  EXIT_BUTTON="JACKPOT.BTN.EXIT";
	
	public  String  CLOSE_BUTTON="JACKPOT.BTN.CLOSE";
	
	public  String  KEYBOARD_BUTTON="JACKPOT.BTN.KEYBOARD";
	
	public  String SLOT_ATTENDANT_ID = "JACKPOT.SLOT.ATTENDANT.ID";
	
	public  String EMPLOYEE_PASSWORD="JACKPOT.EMPLOYEE.PASSWORD";
	
	public  String SLOT_NUMBER="JACKPOT.SLOT.NUMBER";
	
	public  String SEQUENCE_NUMBER="JACKPOT.SEQUENCE.NUMBER";
	
	public  String AUTHORIZATION_EMPLOYEE_ID_ONE="JACKPOT.AUTH.EMPLOYEE.ID.ONE";
	
	public  String AUTHORIZATION_EMPLOYEE_ID_TWO="JACKPOT.AUTH.EMPLOYEE.ID.TWO";
	
	public  String AUTHORIZATION_PASSWORD_ONE="JACKPOT.AUTH.EMPLOYEE.PASSWORD.ONE";
	
	public  String AUTHORIZATION_PASSWORD_TWO="JACKPOT.AUTH.EMPLOYEE.PASSWORD.TWO";
		
	public  String SUBMIT_BUTTON="JACKPOT.BTN.SUBMIT";
	
	public  String PREVIOUS_BUTTON ="JACKPOT.BTN.PREVIOUS";
		
	public  String NEXT_BUTTON ="JACKPOT.BTN.NEXT";
	
	public  String CANCEL_BUTTON="JACKPOT.BTN.CANCEL";
	
	public  String CLEAR_BUTTON="JACKPOT.BTN.CLEAR";
	
	public  String OK_BUTTON="JACKPOT.BTN.OK";
	
	public  String YES_BUTTON="JACKPOT.BTN.YES";
	
	public  String NO_BUTTON="JACKPOT.BTN.NO";
	
	public   String PENDING_JACKPOT_BUTTON = "JACKPOT.BTN.PENDING";
	
	public  String MANUAL_JACKPOT_BUTTON = "JACKPOT.BTN.MANUAL";
	
	public  String VOID_BUTTON = "JACKPOT.BTN.VOID";
	
	public  String REPRINT_BUTTON = "JACKPOT.BTN.REPRINT";
	
	public  String DISPLAY_BUTTON = "JACKPOT.BTN.DISPLAY";

	public  String WINNING_COMBINATION = "JACKPOT.WINNING.COMBINATION";
	
	public  String PAY_LINE = "JACKPOT.PAYLINE";
	
	public  String COINS_PLAYED = "JACKPOT.COINS.PLAYED";
	
	public  String WINDOW_NUMBER="JACKPOT.WINDOW.NUMBER";
	
	public  String PLAYER_CARD="JACKPOT.PLAYER.CARD";
	
	public  String DISPLAY_JACKPOT_DETAILS ="JACKPOT.DISPLAY.DETAILS";
	
	public  String DISPLAY_PENDING_JACKPOT_SLIPS_DETAILS ="JACKPOT.DISPLAY.PENDING.SLIPS.DETAILS";
	
	public  String PLAYER_NAME="JACKPOT.PLAYER.NAME";
	
	public  String VOID_JACKPOT ="JACKPOT.VOID";
	
	public  String REPRINT_JACKPOT ="JACKPOT.REPRINT";
	
	public  String WELCOME_NOTE_ON_TOUCH_SCREEN_HOMEPAGE ="GENERAL.TOUCHSCREEN.WELCOME";
	
	public  String SELECT_NOTE_ON_TOUCH_SCREEN_HOMEPAGE ="GENERAL.TOUCHSCREEN.NOTE";	
	
	public   String CREDIT_METER_HP_YES_LABEL ="JACKPOT.CREDIT.METER.HANDPAY" ;
	
	public   String CREDIT_METER_HP_NO_LABEL="JACKPOT.NON.CREDIT.METER.HANDPAY" ;
	
	public    String EXPRESS_JP_AMOUNT_LABEL="JACKPOT.AMOUNT"; 
	
	public   String HAND_PAID_AMOUNT_LABEL="JACKPOT.HANDPAID.AMOUNT";
	
	public   String MACHINE_PAID_AMOUNT_LABEL="JACKPOT.MACHINEPAID.AMOUNT";
	
	public   String DAY_SHIFT_LABEL="JACKPOT.SHIFT.DAY";
	
	public   String SWING_SHIFT_LABEL="JACKPOT.SHIFT.SWING";
	
	public   String GRAVEYARD_SHIFT_LABEL="JACKPOT.SHIFT.GRAVEYARD";
	
	public   String POUCH_PAY_YES_LABEL="JACKPOT.TYPE.POUCHPAY";
	
	public   String POUCH_PAY_NO_LABEL="JACKPOT.TYPE.NON.POUCHPAY";
	
	public   String JACKPOT_TYPE_NORMAL_LABEL="JACKPOT.TYPE.NORMAL";
	
	public   String JACKPOT_TYPE_PROGRESSIVE_LABEL="JACKPOT.TYPE.PROGRESSIVE";
	
	public   String JACKPOT_TYPE_CANCELED_CREDITS_LABEL="JACKPOT.TYPE.CANCELED.CREDITS";
	
	public   String PROMOTIONAL_JACKPOT_YES_LABEL="JACKPOT.TYPE.PROMOTIONAL";
	
	public   String PROMOTIONAL_JACKPOT_NO_LABEL="JACKPOT.TYPE.NON.PROMOTIONAL";
	
	public   String NO_TAX_LABEL="JACKPOT.TAX.NO";
	
	public   String STATE_TAX_LABEL="JACKPOT.TAX.STATE";
	
	public   String FEDERAL_TAX_LABEL="JACKPOT.TAX.FEDERAL";
	
	public   String STATE_PLUS_FEDERAL_TAX_LABEL="JACKPOT.TAX.STATE.FEDERAL";
	
	public   String PENDING_JACKPOT_SLIPS_DISPLAY="JACKPOT.PENDING.SLIPS.DISPLAY";
	
	public   String STAND_NUMBER="JACKPOT.STAND.NUMBER";
	
	public   String DATE_OR_TIME="JACKPOT.DATE.TIME";
	
	public   String EMPLOYEE_NAME="JACKPOT.EMPLOYEE.NAME";
	
	public   String MANDATORY_LABEL = "FRAMEWORK.MANDATORY.LABEL";
	
	public String  NON_CARDED_EXPRESS_JACKPOT_YES="JACKPOT.CONTINUE.NORMAL";

	public String  NON_CARDED_EXPRESS_JACKPOT_NO="JACKPOT.ABORT";
		
	public String SHIFT_GROUP_HEADING_LABEL="JACKPOT.SHIFT.HEADER";
	
	public String NON_CARDED_EXPRESS_JACKPOT_GROUP_HEADING_LABEL="JACKPOT.NON.CARDED.EXPRESS.JACKPOT.HEADER";
	
	public String PROMOTIONAL_JACKPOT_GROUP_HEADING_LABEL="JACKPOT.PROMOTIONAL.HEADER";

	public String JACKPOT_TYPE_GROUP_HEADING_LABEL="JACKPOT.TYPE.HEADER";
	
	public String POUCH_PAY_GROUP_HEADING_LABEL="JACKPOT.POUCHPAY.HEADER";

	public String TAX_GROUP_HEADING_LABEL="JACKPOT.TAX.HEADER";
	
	public String CREDIT_METER_H_P_GROUP_HEADING_LABEL="JACKPOT.CREDIT.METER.HANDPAY.HEADER";
	
	public String DISPLAY_TOTAL_PAGE_COUNT="JACKPOT.TOTAL.PAGE.COUNT";
	
	public String STAND_OR_SEQ_NUMBER="JACKPOT.STAND.OR.SEQ.NUMBER";
	
	public String SLOT_OR_SEQ_NUMBER="JACKPOT.SLOT.OR.SEQ.NUMBER";
	
	public String PRINTER_BUTTON="JACKPOT.BTN.PRINTER";
	
	public String THEME_LABEL="JACKPOT.GAME.INFO.THEME.LABEL";
	
	public String DENOMINATION_LABEL="JACKPOT.GAME.INFO.DENOM.LABEL";
	
	public String OR_LABEL="JACKPOT.OR.LABEL";
	
	public String BALLY_COPYRIGHT_LABEL="JACKPOT.BALLY.COPYRIGHT.LABEL";
	
	public String SEQUENCE_NUMBER_OR_ALL = "JACKPOT.SEQUENCE.NUMBER.OR.ALL";
	
	public String NUMBER_OF_MINUTES="JACKPOT.NUMBER.OF.MINUTES";
	
	public String JACKPOT_SLIP_DETAILS="JACKPOT.SLIP.DETAILS";
	
	public String JACKPOT_TYPE="JACKPOT.TYPE";
	
	public String TAX_TYPE="JACKPOT.TAX";
	
	public String SHIFT="JACKPOT.SHIFT";
	
	public String JACKPOT_ORIGINAL_AMOUNT_LABEL="JACKPOT.ORIGINAL.AMOUNT";
	
	public String MODULE_NAME="JACKPOT";
	
	public String HOME="JACKPOT.HOME.LABEL";
	
	public String PREFERENCE="JACKPOT.PREFERENCE.LABEL";
	
	public String SEQUENCE_NUMBER_FOR_PROCESSED_SLIPS= "JACKPOT.SEQUENCE.NO.FOR.PROCESSED.SLIPS";
	
	public String SLOT_NUMBER_FOR_PENDING_SLIPS= "JACKPOT.SLOT.NO.ALL.FOR.PENDING.SLIPS";
	
	public String SLOT_LOCATION_NUMBER_FOR_PENDING_SLIPS="Slot Location No/All(A)(For pending slips)";// TO BE ADDED TO DB
	
	public String PRINT_PENDING_VOID_REPORT= "JACKPOT.BTN.PRINT.REPORT";
	
	public  String REPORT_BUTTON = "JACKPOT.BTN.REPORT";
	
	public  String FROM_DATE_TIME = "JACKPOT.FROM.DATE.TIME";
	
	public  String TO_DATE_TIME = "JACKPOT.TO.DATE.TIME";
	
	public  String PRINT_JPVOID_SEQ_NO = "JACKPOT.JPVOID.RPT.SEQ.NUMBER";
	
	public  String PRINT_JPVOID_DATE = "JACKPOT.JPVOID.RPT.SLIP.DATE";
	
	public  String PRINT_JPVOID_TIME = "JACKPOT.JPVOID.RPT.SLIP.TIME";
	
	public  String PRINT_JPVOID_SLOT_NO = "JACKPOT.JPVOID.RPT.SLOT.NUMBER";
	
	public  String PRINT_JPVOID_STAND_NO = "JACKPOT.JPVOID.RPT.SLOT.LOCATION";
	
	public  String PRINT_JPVOID_DENOM = "JACKPOT.JPVOID.RPT.SLOT.DENOM";
	
	public  String PRINT_JPVOID_AMOUNT = "JACKPOT.JPVOID.RPT.AMOUNT";
	
	public  String SEQUENCE_NUMBER_PRIOR ="JACKPOT.SEQUENCE.NUMBER.PRIOR";
	
	public  String PENDING_JP_HEADING = "JACKPOT.PENDING.HEADING";
	
	public  String MANUAL_JP_HEADING = "JACKPOT.MANUAL.HEADING";
	
	public  String VOID_JP_HEADING = "JACKPOT.VOID.HEADING";
	
	public  String REPRINT_JP_HEADING = "JACKPOT.REPRINT.HEADING";
	
	public  String DISPLAY_JP_HEADING = "JACKPOT.DISPLAY.HEADING";
	
	public  String REPORT_JP_HEADING = "JACKPOT.REPORT.HEADING";	
	
	public  String PRINT_JPVOID_HEADING = "JPVOID.VOID.RPT.HEADER";
	
	public  String PRINT_JP_TYPE_NORMAL_REGULAR = "JACKPOT.PRINT.TYP.NORMAL.REG";//"NORMAL REGULAR JACKPOT";
	
	public  String PRINT_JP_TYPE_NORMAL_PROGRESSIVE = "JACKPOT.PRINT.TYP.NORMAL.PROG";//"NORMAL PROGRESSIVE JACKPOT";
	
	public  String PRINT_JP_TYPE_NORMAL_LINKED_PROGRESSIVE = "JACKPOT.PRINT.TYP.NORMAL.LINKED.PROG";//"NORMAL LINKED PROGRESSIVE JACKPOT";
	
	public  String PRINT_JP_TYPE_NORMAL_SYSTEM_GAME = "JACKPOT.PRINT.TYP.NORMAL.SYS.GAME";//"NORMAL SYSTEM GAME JACKPOT";
	
	public  String PRINT_JP_TYPE_NORMAL_CANCEL_CREDIT = "JACKPOT.PRINT.TYP.NORMAL.CANCEL.CREDIT";//"NORMAL CANCEL CREDIT JACKPOT";
	
	public  String PRINT_JP_TYPE_EXPRESS_REGULAR = "JACKPOT.PRINT.TYP.EXPRESS.REG";//"EXPRESS REGULAR JACKPOT";
	
	public  String PRINT_JP_TYPE_EXPRESS_PROGRESSIVE = "JACKPOT.PRINT.TYP.EXPRESS.PROG";//"EXPRESS PROGRESSIVE JACKPOT";
	
	public  String PRINT_JP_TYPE_EXPRESS_LINKED_PROGRESSIVE = "JACKPOT.PRINT.TYP.EXPRESS.LINKED.PROG";//"EXPRESS LINKED PROGRESSIVE JACKPOT";
	
	public  String PRINT_JP_TYPE_EXPRESS_SYSTEM_GAME = "JACKPOT.PRINT.TYP.EXPRESS.SYS.GAME";//"EXPRESS SYSTEM GAME JACKPOT";
	
	public  String PRINT_JP_TYPE_EXPRESS_CANCEL_CREDIT = "JACKPOT.PRINT.TYP.EXPRESS.CANCEL.CREDIT";//"EXPRESS CANCEL CREDIT JACKPOT";
			
	public  String PRINT_JP_TYPE_POUCH_PAY_REGULAR = "JACKPOT.PRINT.TYP.POUCHPAY.REG";//"POUCH PAY REGULAR JACKPOT";
	
	public  String PRINT_JP_TYPE_POUCH_PAY_SYSTEM_GAME = "JACKPOT.PRINT.TYP.POUCHPAY.SYS.GAME";//"POUCH PAY SYSTEM GAME JACKPOT";
	
	public  String PRINT_JP_TYPE_POUCH_PAY_CANCEL_CREDIT = "JACKPOT.PRINT.TYP.POUCHPAY.CANCEL.CREDIT";//"POUCH PAY CANCEL CREDIT JACKPOT";
	
	public  String PRINT_JP_TYPE_POUCH_PAY_PROGRESSIVE = "JACKPOT.PRINT.TYP.POUCHPAY.PROG";//"POUCH PAY PROGRESSIVE JACKPOT";
	
	public  String PRINT_JP_TYPE_MANUAL_REGULAR = "JACKPOT.PRINT.TYP.MANUAL.REG";//"MANUAL REGULAR JACKPOT";
		
	public  String PRINT_JP_TYPE_MANUAL_PROGRESSIVE = "JACKPOT.PRINT.TYP.MANUAL.PROG";//"MANUAL PROGRESSIVE JACKPOT";
	
	public  String PRINT_JP_TYPE_MANUAL_CANCEL_CREDIT = "JACKPOT.PRINT.TYP.MANUAL.CANCEL.CREDIT";//"MANUAL CANCEL CREDIT JACKPOT";
	
	public  String PRINT_PROCESS_EMP_ID = "JACKPOT.PRINT.PROCESS.EMP.ID";// PROCESS EMP ID
	
	public  String PRINT_SLOT_NO = "JACKPOT.PRINT.ACNF.NUMBER";//SLOT
	
	public  String PRINT_SEQ_NO = "JACKPOT.PRINT.SEQ.NUMBER";//SEQUENCE NO
	
	public  String PENDING_JP_ARE_VOIDED = "JACKPOT.PENDING.ARE.VOIDED";//PENDING JACKPOTS ARE VOIDED
		
	public  String JP_PRINTER_PERF_CANNOT_BE_SET_AFTER_LOGIN = "JACKPOT.PRINTER.PERF.NOT.SET.AFTER.LOG.IN";//Note: Jackpot printer preferences value can be set only when logged out
	
	public  String JP_AREA_PERF_CAN_BE_SET_AFTER_LOGIN = "JACKPOT.AREA.PERF.SET.AFTER.LOG.IN";//Note: Jackpot printer preferences value can be set only after loggin in
		
	public  String JP_PREF_AVAILABLE_AREAS = "JACKPOT.PREF.AVAILABLE.AREA";//Available Areas
	
	public  String JP_PREF_SELECTED_AREAS = "JACKPOT.PREF.SELECTED.AREA";//Selected Areas
	
	public  String ASSOCIATED_PLAYER_CARD = "JACKPOT.ASS.PLY.CARD";//Org Player Card

	public  String PRINT_CASINO_NAME = "JACKPOT.PRINT.CASINO.NAME";//CASINO NAME
	
	public  String PRINTER_PREF = "JACKPOT.PRINTER.PREF";//Printer
	
	public  String AREA_PREF = "JACKPOT.AREA.PREF";//Area
	
	public String CTRL_BTN_FORWARD = "Forward";
	
	public String CTRL_BTN_BACKWARD = "Backward";
	
	String JACKPOT_HPJP_AMOUNT = "JACKPOT.PRINT.HAND.PAID.AMOUNT";
	
	String JACKPOT_NET_AMOUNT = "JACKPOT.PRINT.NET.AMOUNT";
	
	String JACKPOT_TOTAL_TAX_AMOUNT = "JACKPOT.PRINT.TAX.AMOUNT";
	
	String JACKPOT_REPORT_HEADING = "JACKPOT.PRINT.REPORT.HEADER";
	
	String JACKPOT_TOTAL_VOIDED_AMOUNT = "JACKPOT.PRINT.VOID.AMOUNT";
	
	String JACKPOT_PRINTED_DATE= "JACKPOT.PRINT.PRINTED.DATE";
	
	String JACKPOT_PRINT_ACNF_NUMBER = "JACKPOT.PRINT.ACNF.NUMBER";
	
	String JACKPOT_PRINT_SEQ_NUMBER = "JACKPOT.PRINT.SEQ.NUMBER";
	
	String JACKPOT_PRINT_TOTAL_JACKPOT_AMOUNT = "JACKPOT.PRINT.TOTAL.JACKPOT.AMOUNT";
	
	
	
	
	//keypad Amount in words constants
	
	
	String LBL_ONE="JACKPOT.ONE";
	String LBL_TWO="JACKPOT.TWO";
	String LBL_THREE="JACKPOT.THREE";
	String LBL_FOUR="JACKPOT.FOUR";
	String LBL_FIVE="JACKPOT.FIVE";
	String LBL_SIX="JACKPOT.SIX";
	String LBL_SEVEN="JACKPOT.SEVEN";
	String LBL_EIGHT="JACKPOT.EIGHT";
	String LBL_NINE="JACKPOT.NINE";
	
	String LBL_TEN="JACKPOT.TEN";	
	String LBL_ELEVEN="JACKPOT.ELEVEN";
	String LBL_TWELVE="JACKPOT.TWELVE";
	String LBL_THIRTEEN="JACKPOT.THIRTEEN";
	String LBL_FOURTEEN="JACKPOT.FOURTEEN";
	String LBL_FIFTEEN="JACKPOT.FIFTEEN";
	String LBL_SIXTEEN="JACKPOT.SIXTEEN";
	String LBL_SEVENTEEN="JACKPOT.SEVENTEEN";
	String LBL_EIGHTEEN="JACKPOT.EIGHTEEN";
	String LBL_NINETEEN="JACKPOT.NINETEEN";
	
	String LBL_TWENTY="JACKPOT.TWENTY";
	String LBL_THIRTY="JACKPOT.THIRTY";
	String LBL_FORTY="JACKPOT.FORTY";
	String LBL_FIFTY="JACKPOT.FIFTY";
	String LBL_SIXTY="JACKPOT.SIXTY";
	String LBL_SEVENTY="JACKPOT.SEVENTY";
	String LBL_EIGHTY="JACKPOT.EIGHTY";
	String LBL_NINETY="JACKPOT.NINETY";
	
	String LBL_HUNDRED="JACKPOT.HUNDRED";
	String LBL_THOUSAND="JACKPOT.THOUSAND";
	String LBL_MILLION="JACKPOT.MILLION";
	String LBL_BILLION="JACKPOT.BILLION";
	String LBL_TRILLION="JACKPOT.TRILLION";
	
	String LBL_DOLLARS="JACKPOT.DOLLARS";
	String LBL_DOLLAR="JACKPOT.DOLLAR";
	String LBL_CENTS="JACKPOT.CENTS";
	String LBL_CENT="JACKPOT.CENT";
	
	String LBL_AND_NO="JACKPOT.AND.NO";
	String LBL_AND_ONE="JACKPOT.AND.ONE";
	String LBL_AND="JACKPOT.AND";
	String LBL_ZERO="JACKPOT.ZERO";
	
	
	
	
	
}
