/*****************************************************************************
 * $Id: IDBLabelKeyConstants.java,v 1.87.2.1.1.0, 2013-10-25 16:52:01Z, Sornam, Ramanathan$
 * $Date: 10/25/2013 11:52:01 AM$
 *****************************************************************************
 *           Copyright (c) 2006 Bally Technology  1977 - 2007
 *  All programs and files on this medium are operated under U.S.
 *  patents Nos. 5,429,361 & 5,470,079
 *
 *  All programs and files on this medium are copyrighted works and all rights
 *  are reserved.  Duplication of these in whole or in part is prohibited
 *  without written permission from Bally Gaming Inc.,
 *  Las Vegas, Nevada, U.S.A
 *****************************************************************************/

package com.ballydev.sds.voucherui.constants;


/**
 * Interface that contains all the database keys for the labels 
 *
 */
public interface IDBLabelKeyConstants {
	String  MODULE_NAME						 = "Voucher";

	String LBL_HOME_PAGE_NOTE				 = "VOUCHER.HOME.PAGE.NOTE";

	//	Button Labels
	String LBL_REDEEMVOUCHER				 = "VOUCHER.REDEEMVOUCHER";
	String LBL_PRINTVOUCHER					 = "VOUCHER.PRINTVOUCHER";
	String LBL_VOIDVOUCHER				  	 = "VOUCHER.VOIDVOUCHER";
	String LBL_REPORTS				 		 = "VOUCHER.REPORTS";
	String LBL_ENQUIRE_VOUCHER				 = "VOUCHER.ENQUIRE.VOUCHER";
	String LBL_REDEEM_VOUCHER				 = "VOUCHER.REDEEM.VOUCHER";
	String LBL_PRINT_VOUCHER				 = "VOUCHER.PRINT.VOUCHER" ;
	String LBL_VOID_VOUCHER					 = "VOUCHER.VOID.VOUCHER";
	String LBL_VOUCHER_MAIN_MENU_			 = "VOUCHER.VOUCHER.MAIN.MENU.";
	String LBL_RECONCILIATION				 = "VOUCHER.RECONCILIATION";
	String LBL_ADMINISTRATION				 = "VOUCHER.ADMINISTR;ION";
	String LBL_LOG_OUT						 = "VOUCHER.LOG.OUT";
	String LBL_VERIFY_OFFLINE				 = "VOUCHER.VERIFY.OFFLINE";

	String LBL_REDEEM_VOUCHER_HEADER		 = "VOUCHER.REDEEM.VOUCHER.HEADER";
	String LBL_ENQUIRE_VOUCHER_HEADER		 = "VOUCHER.ENQUIRE.VOUCHER.HEADER";
	String LBL_PRINT_VOUCHER_HEADER			 = "VOUCHER.PRINT.VOUCHER.HEADER" ;

	String LBL_MENU					 		 = "VOUCHER.MENU";
	String LBL_SUBMIT						 = "VOUCHER.SUBMIT";
	String LBL_CANCEL						 = "VOUCHER.CANCEL";
	String LBL_CANCEL_REDEEM				 = "VOUCHER.REDEEM.CANCEL";
	String LBL_REDEEM						 = "VOUCHER.REDEEM";
	String LBL_EXIT							 = "VOUCHER.EXIT";
	String LBL_MULTI_REDEEM					 = "VOUCHER.MULTI.REDEEM";
	String LBL_VOID							 = "VOUCHER.VOID";
	String LBL_PRINT						 = "VOUCHER.PRINT";
	String LBL_SUBMIT_BARCODE				 = "VOUCHER.SUBMIT.BARCODE";
	
	String LBL_BRWOSE_XML					 = "VOUCHER.BRWOSE.XML";
	String LBL_UPLOAD_FILE					 = "VOUCHER.UPLOAD.XMLFILE";
	
	String LBL_BAR_CODE						 = "VOUCHER.BAR.CODE";
	String LBL_AMOUNT						 = "VOUCHER.AMOUNT";
	String LBL_VOUCHER_COUPON_DETAILS		 = "VOUCHER.VOUCHER.COUPON.DETAILS";
	String LBL_STATE						 = "VOUCHER.STATE";
	String LBL_EFFECTIVE_DATE				 = "VOUCHER.EFFECTIVE.DATE";
	String LBL_EXPIRE_DATE					 = "VOUCHER.EXPIRE.DATE";
	String LBL_LOCATION						 = "VOUCHER.LOCATION";
	String LBL_OFFLINE						 = "VOUCHER.OFFLINE";
	String LBL_TKT_TYPE						 = "VOUCHER.TKT.TYPE";
	String VOU_CANNOT_GREATER_THAN			 = "VOU.CANNOT.GREATER.THAN";
	String LBL_PLAYER_ID					 = "VOUCHER.PLAYER.ID";
	String LBL_STC_VOID_TICKET_SCREEN		 = "VOUCHER.STC.VOID.TICKET.SCREEN";
	
	//String LBL_STC_PRINT_TICKET_SCREEN	 = "VOUCHER.STC.PRINT.TICKET.SCREEN") +AppContextValues.getInstance().getTicketText();

	String LBL_MULTI_VOUCHER_COUPON_REDEEM_TOTALS	 = "VOUCHER.MULTI.VOUCHER.COUPON.REDEEM.TOTALS";
	
	String LBL_OF_VOUCHERS_COUPONS			 = "VOUCHER.OF.VOUCHERS/COUPONS";
	String LBL_RESET_TOTAL					 = "VOUCHER.RESET.TOTAL";
	String LBL_SHOW_TOTAL					 = "VOUCHER.SHOW.TOTAL";
	String LBL_TOTAL_AMOUNT					 = "VOUCHER.TOTAL.AMOUNT";
	String LBL_TOTAL_COUNT					 = "VOUCHER.PRINT.TOTAL.COUNT";

	String LBL_ENTER_TICKET_AMOUNT			 = "VOUCHER.ENTER.TICKET.AMOUNT";
	String LBL_PRINT_TOTAL_AMOUNT			 = "VOUCHER.PRINT.TOTAL.AMOUNT";

	String LBL_COUNT						 = "VOUCHER.COUNT";
	String LBL_PRINT_COUNT					 = "VOUCHER.PRINT.COUNT";

	//String LBL_OVERRIDE_VOUCHER_AUTHENTICATION	 = "VOUCHER.OVERRIDE.VOUCHER.AUTHENTICATION",new String[] {AppContextValues.getInstance().getTicketText()});
	//String LBL_USER_ID					 = "VOUCHER.USER.ID");
	
	String LBL_PASSWORD						 = "VOUCHER.PASSWORD";
	String LBL_REASON_FOR_OVERRIDE			 = "VOUCHER.REASON.FOR.OVERRIDE";

	//#Reconciliation Main composite Page
	//Cashier Id
	//String LBL_SET_EMPLOYEE				 = "VOUCHER.SET.EMPLOYEE");
	//Kiosk Number
	String LBL_SET_KIOSK					 = "VOUCHER.SET.KIOSK";

	String LBL_LOC_CODE						 = "VOUCHER.LOC.CODE";

	//Reconciliation
	//String LBL_HEADING_RECONCILIATION		 = AppContextValues.getInstance().getTicketText()+ "VOUCHER.HEADING.RECONCILIATION") ;
	
	//Start Time
	String LBL_START_TIME					 = "VOUCHER.START.TIME";
	
	//End Time
	String LBL_END_TIME						 = "VOUCHER.END.TIME";

	String LBL_BATCH_VALUE_NOT_SET			 = "VOUCHER.BATCH.VALUE.NOT.SET";

	//Set Employee Details
	String LBL_SET_EMP_DETAIL				 = "VOUCHER.SET.EMP.DETAILS";
	//"  Cashier  "
	String BTN_SET_EMPLOYEE					 = "VOUCHER.TOGGLE.SET.EMPLOYEE";
	//"  Kiosk  "
	String BTN_SET_KIOSK					 = "VOUCHER.TOGGLE.SET.KIOSK";

	//"Manual Voucher Coupon Scan"
	//String LBL_HEADING_MANUAL_VOUCHER_COUPAN_SCAN	 = "VOUCHER.HEADING.MANUAL.VOUCHER.COUPAN.SCAN",new String[] {AppContextValues.getInstance().getTicketText()});
	
	//"Voucher/Coupon"
	String LBL_BARCODE 						 = "VOUCHER.BARCODE";
	//"Add To Batch"
	String BTN_ADD_TO_BATCH					 = "VOUCHER.ADD.TO.BATCH";
	//"Submit"
	String BTN_SUBMIT						 = "VOUCHER.SUBMIT";
	//"Current Scan Details"
	String LBL_CURRENT_SCN_DTL				 = "VOUCHER.CURRENT.SCAN.DETAIL";
	//"Details"
	String LBL_DETAILS						 = "VOUCHER.DETAILS";
	//"Accepted"
	String LBL_ACCEPTED						 = "VOUCHER.ACCEPTED";
	//"No Read"
	String LBL_NO_READ						 = "VOUCHER.NO.READ";
	//"Total"
	String LBL_TOTAL						 = "VOUCHER.TOTAL";
	//"Uncommitted"
	String LBL_UNCOMMITED					 = "VOUCHER.UNCOMMITTED";
	//"Please ensure the tickets are scanned or entered"
	String MSG_ENSURE_TICKETS_SCANNED		 = "VOUCHER.MSG.ENSURE.TICKETS.SCANNED";
	//"Batch is created Succesfully"
	String MSG_BATCH_CREATION_SUCCESS		 = "VOUCHER.MSG.BATCH.CREATION.SUCCESS";
	//"What do you want to Reconcile ?"
	String GRP_RECON_TYPE_HEADING			 = "VOUCHER.GRP.RECON.TYPE.HEADING";
	//"Choose Batch Time"
	String GRP_RECON_BATCH_TIME_HEADING		 = "VOUCHER.GRP.RECON.BATCH.TIME.HEADING";
	//"Current Scan Details"
	String GRP_RECN_CURR_SCN_DETAIL_HEADING	 = "VOUCHER.GRP.RECN.CURR.SCN.DETAIL.HEADING";
	//"XML Upload Detail
	String GRP_RECN_XML_UPLOAD_HEADING	 	 = "VOUCHER.GRP.RECN.XML.UPLOAD.HEADING";
	
	String LBL_UPLOAD_XML						 = "VOUCHER.UPLOAD.XML";


	//Reconciliation Batch Detail composite Page
	//Batch # : 
	String LBL_BATCH_NO						 = "VOUCHER.BATCH.NUMBER";
	//Employee: 
	String LBL_EMPLOYEE_ID					 = "VOUCHER.EMPLOYEE";
	//Kiosk:
	String LBL_KIOSK_ID						 = "VOUCHER.KIOSK";
	//Voucher Count: 
	String LBL_VOUCHER_COUNT				 =  "VOUCHER.VOUCHER.COUNT";
	//Voucher $: 
	String LBL_VOUCHER_$					 =  "VOUCHER.VOUCHER.AMOUNT";
	//Coupon Count: 
	String LBL_COUPAN_COUNT					 = "VOUCHER.COUPAN.COUNT";
	//Coupon $: 
	String LBL_COUPAN_$						 = "VOUCHER.COUPAN.AMOUNT";

	String DISPLAY_TOTAL_PAGE_COUNT			 = "VOUCHER.TOTAL.PAGE.COUNT";
	String DISPLAY_BATCH_DETAILS_TITLE		 = "VOUCHER.BATCH.DETAILS.TITLE";
	String TKT_LOCATION						 = "VOUCHER.TICKET.LOCATION";
	String LBL_OVERRIDE						 = "VOUCHER.OVERRIDE";
	String TKT_BARCODE						 = "VOUCHER.TICKET.BARCODE";
	String TKT_TYPE							 = "VOUCHER.TICKET.TYPE";
	String TKT_AMOUNT						 = "VOUCHER.TICKET.AMOUNT";
	String REASON							 = "VOUCHER.REASON";
	String CANCEL_BUTTON					 = "VOUCHER.CANCEL.BUTTON";
	String RELOAD_BATCH_DETAILS				 = "VOUCHER.RELOAD.BATCH.DETAILS";
	String QUESTIONABLE_VOUCHERS_COUPONS	 = "VOUCHER.QUESTIONABLE.VOUCHERS.COUPONS";
	String PRINT_BATCH_DETAILS				 = "VOUCHER.PRINT.BATCH.DETAILS";
	String DELETE_CURRENT_BATCH				 = "VOUCHER.DELETE.CURRENT.BATCH";
	String CHANGE_LOCATION					 = "VOUCHER.CHANGE.EMPLOYEE";
	String CHANGE_KIOSK						 = "VOUCHER.CHANGE.KIOSK";
	String DISPLAY_VERIFY_OFFLINE_TICKET	 = "VOUCHER.VERIFY.OFFLINE.TICKET";

	//#Reconciliation - Batch Summary composite page
	//Batch 
	String TBL_LBL_BATCH_NO					 = "VOUCHER.TABLE.BATCH.NUMBER";
	//Voucher Count
	String TBL_LBL_VOUCHER_COUNT			 =  "VOUCHER.TABLE.VOUCHER.COUNT";
	//Voucher $
	String TBL_LBL_VOUCHER_$				 = "VOUCHER.TABLE.VOUCHER.AMOUNT";
	//C-Coupon Count
	String TBL_LBL_COUPAN_COUNT				 = "VOUCHER.TABLE.COUPAN.COUNT";
	//C-Coupan $
	String TBL_LBL_COUPAN_AMOUNT			 = "VOUCHER.TABLE.COUPAN.AMOUNT";
	String TBL_LBL_ACCOUNTING_DATE			 = "VOUCHER.TABLE.ACCOUNTING.DATE";
	String TBL_LBL_BATCH_SCAN_DATE			 = "VOUCHER.TABLE.BATCH.SCAN.DATE";

	String TBL_LBL_DATE_TIME				 = "VOUCHER.TABLE.DATE.TIME";
	String TBL_LBL_TRANSACTION				 = "VOUCHER.TABLE.TRANS";
	String TBL_LBL_SOURCE					 = "VOUCHER.TABLE.SOURCE";
	String TBL_LBL_RESULT					 = "VOUCHER.TABLE.RESULT";
	String TBL_LBL_SITEID					 = "VOUCHER.TABLE.SITEID";
	
	String LBL_BATCH_SUMMARY_DETAIL			 = "VOUCHER.BATCH.SUMMARY.DETAIL";
	String BTN_LOAD_SELECTED_BATCH			 = "VOUCHER.LOAD.SELECTED.BATCH";
	String BTN_DELETE_SELECTED_BATCH		 = "VOUCHER.DELETE.SELECTED.BATCH";
	String BTN_CHANGE_EMPLOYEE				 = "VOUCHER.CHANGE.EMPLOYEE";
	String BTN_CHANGE_ASSET					 = "VOUCHER.CHANGE.ASSET";
	String BTN_PRINT_BATCH_SUMMARY			 = "VOUCHER.PRINT.BATCH.SUMMARY";
	//	Do you want to delete the Batch ?
	String MSG_DELETE_CONFIRMATION			 = "VOUCHER.MSG.DELETE.CONFIRMATION";

	//Enter Employee Id
	//String LBL_REQUEST_EMPLOYEE_ID		 = "VOUCHER.REQUEST.EMPLOYEE.ID";
	//Enter Asset Id
	String LBL_REQUEST_ASSET_ID				 = "VOUCHER.REQUEST.ASSET.ID";
	//"Employee ID successfully changed"
	String MSG_EMPLOYEE_ID_CHANGE_SUCCESS	 = "VOUCHER.MSG.EMPLOYEE.ID.CHANGE.SUCCESS";
	//"Asset Id successfully changed"
	String MSG_ASSET_ID_CHANGE_SUCCESS		 = "VOUCHER.MSG.ASSET.ID.CHANGE.SUCCESS";


	//#Reconciliation - QuestionableReconciliation composite
	//Voucher/Coupon Details
	//String LBL_VOUCHER_COUPAN_DETAIL		 = AppContextValues.getInstance().getTicketText()+"VOUCHER.COUPAN.DETAIL");
	String LBL_UPLOADXML= "SOFTCOUNT.UPLOADXML";
	
	//Get Current Batch
	String BTN_GET_CURRENT_BATCH			 = "VOUCHER.GET.CURRENT.BATCH";

	//Print Details
	String BTN_PRINT_DETAILS				 = "VOUCHER.PRINT.DETAILS";

	//"Do you want to proceed ?"
	String MSG_QSTN_WANT_TO_PROCEED			 = "VOUCHER.MSG.QSTN.WANT.TO.PROCEED";
	
	String MSG_NO_BATCH_AVAILABLE			 = "VOUCHER.MSG.NO.BATCH.AVAILABLE";
	String INVALID_USER 					 =  "VOUCHER.MSG.INVALID.USER";
	String USER_PWD_WRONG					 =  "VOUCHER.MSG.PWD.WRONG";
	String USER_NO_PERMISSION				 =  "VOUCHER.MSG.USER.NO.PERMISSION";
	
	//Reconciliation High Speed Scanning
	String MSG_NOEMPID_RESCAN_VOUCHERS  = "VOUCHER.MSG.RECON.NOEMPID.RESCAN.VOUCHERS";
	String MSG_NOBATID_RESCAN_VOUCHERS = "VOUCHER.MSG.RECON.NOBATCHID.RESCAN.VOUCHERS";
	String MSG_ENDTIME_BEFORE_START_RESCAN_VOUCHERS = "VOUCHER.MSG.RECON.ENDTIME.BEFORE.START.RESCAN.VOUCHERS";

//Reconiliaton Xml Upload
	
	String MSG_NOT_VALID_XMLFILEPATH	  = "VOUCHER.MSG.NOT.VALID.XML.PATH";
	String MSG_NOT_WELL_FORMED_XML		  = "VOUCHER.MSG.NOT.WELLFORMED.XML";
	String MSG_NO_BARCODE_IN_XML		  = "VOUCHER.MSG.NO.BARCODE.IN.XML";
	String MSG_NO_EMPLOYEE_IN_XML		  = "VOUCHER.MSG.NO.EMPLOYEE.IN.XML";
	String MSG_NOT_XML_UPLOAD_METHOD	  = "VOUCHER.MSG.NOT.XML.UPLOAD.METHOD";
	String MSG_NO_DATA_IN_XML_UPLOAD	  = "VOUCHER.MSG.NO.DATA.IN.XML.UPLOAD";
	String MSG_NO_XML_BATCH_TO_CREATE	  = "VOUCHER.MSG.NO.XML.BATCH.TO.CREATE";
	String MSG_EMPID_PRE_NOT_MATCH_FOR	  = "VOUCHER.MSG.EMP.ID.PREFIX.NOT.MATCH.FOR";
	String MSG_EMPID_NULL_OR_INVALIDLEN   = "VOUCHER.MSG.EMP.ID.NULL.OR.INVALID.LEN";
	
	
	//#Verify offline Ticket
	//Offline Ticket verified successfully.
	String MSG_OFFLINE_TICKET_VERIFY_SUCCESS = "VOUCHER.MSG.OFFLINE.TKT.VERIFY.SUCCESS";
	//Offline Ticket verification failed.
	String MSG_OFFLINE_TICKET_VERIFY_FAILURE = "VOUCHER.MSG.OFFLINE.TKT.VERIFY.FAILURE";
	//Offline Ticket redeemed successfully.
	String MSG_OFFLINE_TICKET_REDEEM_SUCCESS = "VOUCHER.MSG.OFFLINE.TKT.REDEEM.SUCCESS";
	//Key verification Failed
	String MSG_OFFLINE_TICKET_KEY_VERIFY_FAILED	 = "VOUCHER.MSG.KEY.VERIFICATION.FAILED";

	String LBL_VERIFY						 = "VOUCHER.LBL.VERIFY";
	String LBL_CASH_OUT						 = "VOUCHER.LBL.CASH.OUT";
	String LBL_ENTER_KEY					 = "VOUCHER.LBL.ENTER.KEY";


	String PREFERENCE						 = "Preference";
	String KEYBOARD_BUTTON					 = "KeyBoard";
	String HOME								 = "Home";
	//String LOG_OUT_BUTTON					 = "Logout";

	String VOU_PREF_NOT_SET					 = "VOUCHER.PREF.NOT.SET";
	String VOU_MAX_REDEEM_AMT_EXCEEDED		 = "VOU.MAX.REDEEM.AMT.EXCEEDED";
	String VOU_TKT_PRINT_NOT_ENABLED		 = "VOU.TKT.PRINT.NOT.ENABLED" ;

	String VOU_REDEEM_SITE_NOT_ENABLED		 = "VOU.REDEEM.SITE.NOT.ENABLED";
	String VOUCHER_REDEEM_TICKETS_COUNTS	 = "VOU.REDEEM.TICKETS.COUNT";	
	String VOUCHER_REDEEM_TICKETS_TOTALAMOUNT= "VOU.REDEEM.TICKETS.TOTALAMOUNT";
	String VOUCHER_REDEEM_TICKETS_INPROCESS  = "VOU.REDEEM.TICKETS.PROCESS";
	String VOU_REDEEM_OVERRIDE_REQD			 = "VOU.REDEEM.OVERRIDE.REQD";
	String VOU_NCSH_REDEEM					 = "VOU.NCSH.REDEEM";
	String VOU_NCSH_VOID					 = "VOU.NCSH.VOID";
	String VOU_PROPID_NOT_EQUAL				 = "VOU.PROPID.NOT.EQUAL";
	String VOU_PROPID_NOT_SET				 = "VOU.PROPID.NOT.SET";
	String VOU_PLAYERID_REQD				 = "VOU.PLAYERID.REQD";
	String VOU_PLAYERID_NOT_VALID			 = "VOU.PLAYERID.NOT.VALID";
	String LBL_REPRINT_VOUCHER_HEADER		 = "VOUCHER.REPRINT.VOUCHER.HEADER" ;
	String LBL_ENTER_BARCODE				 = "VOUCHER.ENTER.BARCODE";
	String LBL_REPRINT						 = "VOUCHER.LBL.REPRINT";
	String VOU_STATUS_NOT_ACTIVE			 = "VOU.STATUS.NOT.ACTIVE";

	String VOU_PRINTER_CONNECTION_ERROR		 =  "VOU.PRINTER.CONNECTION.ERROR";
	String VOU_PRINT_CONNECTION_ERROR		 =  "VOU.PRINT.CONNECTION.ERROR";
	String VOU_USER_NOACCESS				 =  "VOU.USER.NOACCESS";
	String VOU_INVALID_LOCATION				 = "VOU.INVALID.LOCATION";
	String LBL_TOTAL_TKTS_TO_PRINT			 = "VOUCHER.PRINT.TOTAL.TO.PRINT";
	String LBL_GRP_TOTAL_TKTS_TO_PRINT		 = "VOUCHER.GRP.PRINT.TOTAL.TO.PRINT";
	String LBL_BARCODE_SUCCESS				 = "VOUCHER.BARCODE.SUCCESS";

	String DELETE_TKT_IN_A_BATCH			 = "VOUCHER.DELETE.TKT.IN.BATCH" ;
	String ADD_TKT_IN_A_BATCH				 = "VOUCHER.ADD.TKT.IN.BATCH" ;
	String UPDATE_TKT						 = "VOUCHER.MODIFY.BARCODE" ;
	String BARCODE_ALREDY_EXISTS			 = "VOUCHER.BARCODE.EXISTS";
	String LBL_ENTER_TICKET					 = "VOUCHER.REQUEST.TICKET";
	String INVALID_TKT_SIZE					 = "VOUCHER.INVALID.TKT.SIZE";
	String INVALID_PLAYER_ID_SIZE			 = "VOUCHER.INVALID.PLAYER.ID.SIZE";
	String ZERO_PLAYER_ID					 = "VOUCHER.ZERO.PLAYER.ID";
	String PROPER_FORMAT_TKT				 = "VOUCHER.PROPER.FORMAT.TKT";
	String INVALID_AMT						 = "VOUCHER.INVALID.AMT";
	String TKT_DELTE_CONFIRM				 = "VOUCHER.TKT.DELETE.CONFIRM";
	String VOU_SERVER_ERROR					 = "VOU.SERVER.ERROR";
	String VOU_DB_ERROR						 = "VOU.DB.ERROR";
	String VOU_REDEEM_PENDING				 = "VOU.REDEEM.PENDING" ;
	String VOU_NO_TKTS_PROPER_VALUE			 = "VOU.NO.TKTS.PROPER.VALUE";
	String VOU_PRINT_SUCCESS				 = "VOU.PRINT.SUCCESS";
	String TKT_PRINT_EXPTN_NO_DRIVER 		 = "VOU.TKT.PRINT.EXPTN.NO.DRIVER";
	String TKT_PRINT_EXPTN_NO_CLASS_DEF 	 = "VOU.TKT.PRINT.EXPTN.NO.CLASS.DEF";
	String TKT_PRINT_EXPTN 					 = "VOU.TKT.PRINT.EXPTN";
	String TKT_PRINT_CONNECTION_SUCESS		 = "VOU.TKT.PRINT.CONNECTION.SUCESS";
	String REC_PRINT_EXPTN_NO_DRIVER 		 = "VOU.REC.PRINT.EXPTN.NO.DRIVER";
	String REC_PRINT_EXPTN_NO_CLASS_DEF 	 = "VOU.REC.PRINT.EXPTN.NO.CLASS.DEF";
	String REC_PRINT_EXPTN 					 = "VOU.REC.PRINT.EXPTN";
	
	//String REC_PRINT_CONNECTION_SUCESS	 = "VOU.REC.PRINT.CONNECTION.SUCESS";
	
	String RECEIPT_PRINT_CONNECTION_SUCESS	 = "VOU.RECEIPT.PRINT.CONNECTION.SUCESS";

	String TKT_CONTAIN_ONLY_NUMERIC			 = "VOU.TKT.CONTAIN.ONLY.NUMERIC";
	String PLAYER_ID_CONTAIN_ONLY_NUMERIC	 = "VOU.PLAYER.ID.CONTAIN.ONLY.NUMERIC";
	String TKT_FIELD_REQD					 = "VOU.TKT.FIELD.REQD";
	String PLAYER_ID_FIELD_REQD				 = "VOU.PLAYER.ID.FIELD.REQD";
	String VOUCHER_BARCODE_CASINO_ID_NOT_MATCH	 = "VOUCHER.BARCODE.CASINO.ID.NOT.MATCH";
	String EMP_FIELD_REQD					 = "VOU.EMP.FIELD.REQD";
	//String INVALID_EMP_FIELD_SIZE			 = "VOU.INVALID.EMP.FIELD.SIZE";
	//String EMP_FIELD_MAX_LENGTH			 = "VOU.EMP.FIELD.MAX.LENGTH";	
	String ASSET_FIELD_MAX_LENGTH			 = "VOU.ASSET.FIELD.MAX.LENGTH";
	String ASSET_FIELD_REQD					 = "VOU.ASSET.FIELD.REQD";
	String EMP_CONTAIN_ONLY_NUMERIC			 = "VOU.EMP.CONTAIN.ONLY.NUMERIC";
	String ASSET_FIELD_ONLY_ALPHA_NUMERIC	 = "VOU.ASSET.FIELD.ONLY.ALPHA.NUMERIC";
	String VOU_LOC_VALUE_SET				 = "VOU.LOC.VALUE.SET";
	String VOU_BATCH_NOT_CREATED 			 = "VOU.BATCH.NOT.CREATED";
	String VOU_INVALID_CASHIER_LOCATION		 = "VOU.INVALID.CASHIER.LOCATION";
	String VOU_CASHIER_LOCATION_NOT_SET		 = "VOU.CASHIER.LOCATION.NOT.SET";
	String VOU_SELECT_TKT_TO_MODIFY			 = "VOU.SELECT.TKT.TO.MODIFY" ;
	String VOU_SELECT_TKT_TO_DELETE			 = "VOU.SELECT.TKT.TO.DELETE";
	String VOU_PRINT_DETAILS_ERROR			 = "VOU.PRINT.DETAILS.ERROR";	
	String VOU_NO_DATA_TO_PRINT				 = "VOU.NO.DATA.TO.PRINT";
	String VOU_PRINT_PREF_NOT_SET			 = "VOU.PRINT.PREF.NOT.SET";
	String VOU_EDIT_VALUE_ALREADY_ENTERED	 = "VOU.EDIT.VALUE.ALREADY.ENTERED";
	String VOU_MISSING_CANNOT_DELETE		 = "VOU.MISSING.CANNOT.DELETE";
	String VOU_PRINT_PREF_VALUE_TO_SET		 = "VOU.PRINT.PREF.VALUE.TO.SET";
	String VOU_TKT_MAX_NO_PRINT_EXCEEDED	 = "VOU.TKT.MAX.NO.PRINT.EXCEEDED";
	String VOU_DISP_REDEEM_MSG				 = "VOU.DISP.REDEEM.MSG";	
	String VOU_LOC_VALUE_SET_CLOSE			 = "VOU.LOC.VALUE.SET.CLOSE";
	String VOU_DISP_EXPTN_NO_DRIVER 		 = "VOU.DISP.EXPTN.NO.DRIVER";
	String VOU_DISP_EXPTN_NO_CLASS_DEF 		 = "VOU.DISP.EXPTN.NO.CLASS.DEF";
	String VOU_DISP_EXPTN 					 = "VOU.DISP.EXPTN";
	String VOU_DISP_CONNECTION_SUCESS		 = "VOU.DISP.CONNECTION.SUCESS";
	String VOU_DISP_PREF_VALUE_TO_SET		 = "VOU.DISP.PREF.VALUE.TO.SET";
	String VOU_INVALID_TKT_TYPE				 = "VOU.INVALID.TKT.TYPE";
	String VOU_SELECT_TABLE_ITEM			 = "VOU.SELECT.TABLE.ITEM";
	String VOU_RECON_VALUES_LOST			 = "VOU.RECON.VALUES.LOST";
	String VOU_RECON_VALUES_CANCEL			 = "VOU.RECON.VALUES.CANCEL";
	String VOU_PERMISSIONTO_OPERATE_VOUCHER	 = "User have not permission to operate Voucher UI.";//"VOU.PERMISSION.TO.OPERATE.VOUCHER";
	
	String VOU_CASHIER_LOCATION_ALREADY_LOGGED_ON	= "VOU.CASHIER.LOCATION.ALREADY.LOGGED.ON";

	String VOU_CASHIER_LOC_ALREADY_LOGGED_ON_LAST	= "VOU.CASHIER.LOCATION.ALREADY.LOGGED.ON.LAST";
	String VOU_CASHIER_LOC_NO_SESSION_FOR_LOGIN	 	= "VOU.CASHIER.LOCATION.NO.SESSION.FOR.LOGIN";
	String VOU_NO_PERMISSION_TO_CREATE_SESSION		= "VOU.NO.PERMISSION.TO.CREATE.SESSION";
	String VOU_NO_PERMISSION_TO_CREATE_AND_SIGNON_SESSION	= "VOU.NO.PERMISSION.TO.CREATE.AND.SIGNON.SESSION";

	//AUDIT TRAIL CONSTANTS
	String BARCODE_ADDED					 = "VOU.BARCODE_ADDED";
	String BARCODE_REDEEMED					 = "VOU.BARCODE.REDEEMED";
	String BARCODE_VOIDED					 = "VOU.BARCODE.VOIDED";
	String BATCH_CREATED					 = "VOU.BATCH.CREATED";
	String BATCH_CASHIER_CHANGED			 = "VOU.BATCH.CASHIER.CHANGED";
	String BATCH_TKT_ADDED					 = "VOU.BATCH.TKT.ADDED";
	String BATCH_TKT_EDITED					 = "VOU.BATCH.TKT.EDITED";
	String BATCH_TKT_DELETED				 = "VOU.BATCH.TKT.DELETED";
	String BATCH_DELETED					 = "VOU.BATCH.DELETED";

	//REPORTS CONSTANTS
	String CASHIER_AND_KIOSK_SESS_REP		 = "VOU.CASHIER.AND.KIOSK.SESS.REP";
	String CASHIER_SESS_REP					 = "VOU.CASHIER.SESS.REP";
	String KIOSK_SESS_REP					 = "VOU.KIOSK.SESS.REP";


	String VOU_DISP_PREF_LOG_OUT_TO_SET		 = "VOU.DISP.PREF.LOG.OUT.TO.SET";

	String VOU_MULTI_AREA_PREF_VALUE_TO_SET	 = "VOU.MULTI.AREA.PREF.VALUE.TO.SET";
	String VOU_EXTPN_REPORTS_FETCH			 = "VOU.EXTPN.REPORTS.FETCH";

	//CASHIER RECEIPT CONSTANTS
	String CASHIER_RECEIPT 					 = "VOU.CASHIER.RECEIPT";
	String VALIDATION_NO 					 = "VOU.VALIDATION.NO";
	String MAC_NO						 	 = "VOU.MAC.NO";
	String LOCATION_ID 						 = "VOU.LOCATION.ID";
	String SYS_GEN_VOU 						 = "VOU.SYS.GEN.VOU";
	String OPERATOR_NO 						 = "VOU.OPERATOR.NO";
	String ISSUE_DATE 						 = "VOU.ISSUE.DATE";
	String PAID_TIME						 = "VOU.PAID.TIME";
	String PAID_DATE 						 = "VOU.PAID.DATE";
	String INVALID_TKT_AMT 					 = "VOUCHER.INVALID.TICKET.AMOUNT";

	String VOU_RECEIPT_PRINT_PREF_VALUE_TO_SET	 = "VOU.RECEIPT.PRINT.PREF.VALUE.TO.SET";

	String VOU_SCANNER_PREF_VALUE_TO_SET	 = "VOU.SCANNER.PREF.VALUE.TO.SET";	
	String VOU_CASHIER_REDEEM_OWN_TKTS		 = "VOU.CASHIER.REEDEM.OWN.TKTS";
	String VOU_CANNOT_VOID_SLOT_TKTS		 = "VOU.CANNOT.VOID.SLOT.TKTS";
	String VOU_CANNOT_VOID_NON_SLOT_TKTS	 = "VOU.CANNOT.VOID.NON.SLOT.TKTS";
	String LBL_PROPERTY_ID					 = "VOUCHER.PREFERENCE.MULTIAREA.PROPERTY.ID";
	String LBL_SELECT_ALL					 = "VOUCHER.SELECT.ALL";
	String TIME_VALUES_CONTINUE				 = "VOUCHER.TIME.VALUES.CONTINUE";

	String SELECT_ONE_OPT_REP				 = "VOUCHER.SELECT.ONE.OPT.REP";
	String VOUCHER_BARCODE_NOT_EXIST		 = "VOUCHER.BARCODE.NOT.EXIST";
	String VOUCHER_ENQUIRE_MODIFY			 = "VOUCHER.ENQUIRE.MODIFY";
	String VOUCHER_ERROR_CONTAIN_NUMERIC	 = "VOUCHER.ERROR.CONTAIN.NUMERIC";
	String VOUCHER_ENQUIRE_MIN_LEN_ERROR	 = "VOUCHER.ENQUIRE.MIN.LEN.ERROR";
	String VOUCHER_ENTER_AMT				 = "VOUCHER.ENTER.AMT";
	String GRP_DETAIL_TYPE_HEADING			 = "VOUCHER.GRP.DETAIL.TYPE.HEADING";
	
	//"  Cashier  "
	String BTN_SET_DETAIL					 = "VOUCHER.TOGGLE.SET.DETAIL";
	//"  Kiosk  "
	String BTN_SET_SUMM						 = "VOUCHER.TOGGLE.SET.SUMM";

	String LBL_REP_TYPE						 = "VOUCHER.REPORT.TYPE";
	String LBL_BTN_CSH						 = "VOUCHER.REP.CASHABLE";
	String LBL_BTN_NCSH						 = "VOUCHER.REP.NCSH";
	String LBL_BTN_CSH_PROMO				 = "VOUCHER.REP.CSHPROMO";

	//String LBL_BTN_TICKET 				 = "VOUCHER.REP.TICKET";
	String LBL_TKT_TYPE_SETTINGS			 = "VOUCHER.TKT.TYPE.SETTINGS";
	String VOUCHER_SELECT_TKT_TYPE			 = "VOUCHER.SELECT.TKT.TYPE";
	String VOUCHER_OVERRIDE_SAME_USER		 =  "VOUCHER.OVERRIDE.SAME.USER" ;

	String VOU_CHK_ENABLE					 = "VOU.CHK.ENABLE";

	String VOU_LOCATION_SYSTEM				 = "VOU.LOCATION.SYSTEM";
	String VOU_TR_REASON_EXPIRED			 = "VOU.TR.REASON.EXPIRED";

	String RECON_RPT_NAME					 = "VOU.RECON.RPT.NAME";
	String RECON_SDS_VERSION				 = "VOU.SDS.VERSION";
	String RECON_QUES_DETAILS_RPT			 = "VOU.RECON.QUES.DETAILS.RPT";
	String RECON_BATCH_DETAILS_RPT			 = "VOU.RECON.BATCH.DETAILS.RPT";
	String RECON_RPT_CASINO_NAME			 = "VOU.RECON.RPT.CASINO.NAME";
	String CASINO_NAME						 = "VOU.TKT.PRINT.CASINO";

	String PRINT_BATCH_HEADING				 = "VOUCHER.PRINT.BATCH.HEADING";
	String PRINT_BATCH_SELECTED				 = "VOUCHER.PRINT.BATCH.SELECTED";
	String PRINT_BATCH_ENTERED				 = "VOUCHER.PRINT.BATCH.ENTERED";
	String PRINT_BATCH_ALL					 = "VOUCHER.PRINT.BATCH.ALL";
	String PRINT_BATCH_ERROR_NUMBER			 = "VOUCHER.PRINT.BATCH.ERROR.NUMBER";
	String PRINT_BATCH_ERROR_NOT_EXIST		 = "VOUCHER.PRINT.BATCH.ERROR.NOT.EXIST";
	
	String PRINT_PAGE_TEXT					 = "VOU.PRINT.PAGE.TEXT";
	
	String VOU_PRINT_EXCEEDED_MAX_DAILY_AMT	 = "VOU.PRINT.EXCEEDED.MAX.DAILY.AMT";
	
	String NO_PRINTER_CONNECTED				 = "VOU.NO.PRINTER.AVAILABLE";

	String TKT_TYPE_NON_SLOT				 = "VOU.LKP.TKTTYP.NSLT.GEN";
	String TKT_TYPE_SLOT					 = "VOU.LKP.TKTTYP.SLT.GEN";
	
	String LBL_DOLLARS						 = "VOU.TKT.DISP.DOLLARS";
	String LBL_DOLLAR						 = "VOU.TKT.DISP.DOLLAR";
	String LBL_CENTS						 = "VOU.TKT.DISP.CENTS";
	String LBL_CENT					         = "VOU.TKT.DISP.CENT";
	
	String VOU_SELECT_ANY_OPTION			 = "VOU.SELECT.ONE.OPTION"; 
	String LBL_SESSION_TRACKING				 = "LBL.SESSION.TRACKING";
	String LBL_CURNT_SESS_DET				 = "LBL.CURNT.SESS.DET";
	String LBL_CURNT_SESS_SUMM				 = "LBL.CURNT.SESS.SUMM";
	String LBL_PREV_SESS_DET				 = "LBL.PREV.SESS.DET";
	String LBL_PREV_SESS_SUMM				 = "LBL.PREV.SESS.SUMM";
	String LBL_EXIT_WITHOUT_CLOSING			 = "LBL.EXIT.WITHOUT.CLOSING";
	String LBL_EXIT_AFTER_CLOSING			 = "LBL.EXIT.AFTER.CLOSING";
	String VOU_GAMING_DATE					 = "VOU.GAMING.DATE";
	String VOU_SESS_START					 = "VOU.SESS.START";
	String VOU_SESS_END						 = "VOU.SESS.END";
	String VOU_TKT_COUNT					 = "VOU.TKT.COUNT";
	String VOU_VALUE						 = "VOU.VALUE"; 
	String VOU_NO_DATA						 = "VOU.NO.DATA";
	String VOU_ERR_PRINT					 = "VOU.ERR.PRINT";
	String VOU_PRINT				 		 = "VOU.PRINT";
	String BARCODE_SCANNER_EXCEPTION		 = "BARCODE.SCANNER.EXCEPTION";
	String VOUCHER_ALREADY_VOIDED_MESSAGEE	 = "VOUCHER.ALREADY.VOIDED.MESSAGEE";
	String VOU_CASHIER_SESSION_ALREADY_LOGGED_ON	  = "VOU.CASHIER.SESSION.ALREADY.LOGGED.ON";
	String VOU_PRINTER_PERF_CANNOT_BE_SET_AFTER_LOGIN = "VOU.PRINTER.PERF.NOT.SET.AFTER.LOG.IN";//Note: Voucher printer preferences value can be set only when logged out

	String VOU_YES  						 = "FRAMEWORK.GENERAL.YES";
	String VOU_NO	  						 = "FRAMEWORK.GENERAL.NO";
	

	//********************Override Functionality***********************//
	
	String LBL_OVERRIDE_VOUCHER					= "LBL.VOUCHER.ENQUIRE.VOUCHER";
	String LBL_OVERRIDE_VOUCHER_HEADER			= "LBL.VOUCHER.OVERRIDE.VOUCHER.HEADER";
	String LBL_TICKET_CREATED_TIME				= "LBL.VOUCHER.TICKET.CREATED.TIME";
	String LBL_ASSET_NUMBER						= "LBL.VOUCHER.ASSET.NUMBER";
	String LBL_TICKET_RESULT					= "LBL.VOUCHER.RESULT";
	String LBL_TICKET_PLAYER_ID					= "LBL.VOUCHER.PLAYER.ID";
	String LBL_TICKET_STATUS					= "LBL.VOUCHER.STATUS";
	String LBL_TICKET_DELETE					= "LBL.VOUCHER.DELETE";
	String LBL_TICKET_REMOVE					= "LBL.VOUCHER.REMOVE";
	String LBL_TICKET_ACCEPT					= "LBL.VOUCHER.ACCEPT";
	String LBL_TICKET_AUTHORISE					= "LBL.VOUCHER.AUTHORISE";
	String LBL_PRINT_TICKET_LOGS				= "LBL.VOUCHER.PRINT.TICKET.LOGS";
	String LBL_OVERRIDE_REASON					= "LBL.VOUCHER.OVERRIDE.REASON";
	String LBL_TICKETS_TOTAL_AMOUNT				= "LBL.VOUCHER.TICKETS.TOTAL.AMOUNT";
	
	//MESSAGE CONSTANTS
	String LBL_UNKNOWN_SLOT_ID					= "LBL.VOUCHER.UNKNOWN.SLOT.ID";
	String LBL_BAD_CRC_IN_TICKET				= "LBL.VOUCHER.BAD.CRC.IN.TICKET";
	String LBL_UNKNOWN_APPLICATION_ERROR		= "LBL.VOUCHER.UNKNOWN.APPLICATION.ERROR";
	String LBL_TICKETS_WITH_WARNING_MSG			= "LBL.VOUCHER.TICKETS.WITH.WARNING.MSG";
	String LBL_ASSET_MISMATCH					= "LBL.VOUCHER.ASSET.MISMATCH";
	String LBL_TICKET_NOT_FROM_SLOT				= "LBL.VOUCHER.TICKET.NOT.FROM.SLOT";
	String LBL_TICKETS_REDEEMED_MESSAGE			= "LBL.VOUCHER.TICKETS.REDEEMED.MESSAGE";
	String LBL_OVERRIDE_LOGS_PRINTER_SELE_MSG	= "LBL.VOUCHER.OVERRIDE.LOGS.PRINTER.SELE.MSG";
	String LBL_BARCODE_ALREADY_EXIST			= "LBL.VOUCHER.BARCODE.ALREADY.EXIST";
	String LBL_TICKETS_WITH_ERROR_MSG			= "LBL.VOUCHER.TICKETS.WITH.ERROR.MSG";
	String LBL_ACCESS_OVERRIDE_SCREEN_MSG		= "LBL.VOUCHER.ACCESS.OVERRIDE.SCREEN.MSG";
	String LBL_NOT_ACCESS_OVERRIDE_SITECONFIG	= "LBL.VOUCHER.NOT.ACCESS.OVERRIDE.SITECONFIG";
	String LBL_TICKET_NOT_FROM_LOGGED_IN_SITE	= "LBL.VOUCHER.TICKET.NOT.FROM.LOGGIED.IN.SITE";
	
	//TABLE VALUES
	//Success
	String LBL_VOU_SUCCESS						= "LBL.VOUCHER.SUCCESS";
	//Errors
	String LBL_VOU_INVALID_LOCATION				= "LBL.VOUCHER.INVALID.LOCATION";
	String LBL_VOU_CRC_CHECK_FAILED				= "LBL.VOUCHER.CRC.CHECK.FAILED";
	String LBL_VOU_RESTRICTED_LOCATION 			= "LBL.VOUCHER.RESTRICTED.LOCATION";
	String LBL_VOU_MAX_REDEEMED_AMOUNT_EXCEEDED = "LBL.VOUCHER.MAX.REDEEMED.AMOUNT.EXCEEDED";
	String LBL_VOU_UNKNOWN_APPLICATION_ERROR 	= "LBL.VOUCHER.UNKNOWN.APPLICATION.ERROR";
	String LBL_VOU_TICKET_ALREADY_REDEEMED 		= "LBL.VOUCHER.TICKET.ALREADY.REDEEMED";
	String LBL_VOU_TICKET_UNREDEEMABLE	 		= "Ticket Unredeemable";//"LBL.VOUCHER.TICKET.TICKET.UNREDEEMABLE";
	//Warnings
	String LBL_VOU_PREV_TICKET_OUT_OF_SEQUENCE	= "LBL.VOUCHER.PREV.TICKET.OUT.OF.SEQUENCE";
	String LBL_VOU_NEXT_TICKET_OUT_OF_SEQUENCE 	= "LBL.VOUCHER.NEXT.TICKET.OUT.OF.SEQUENCE";
	String LBL_VOU_TICKET_ALREADY_EXISTS		= "LBL.VOUCHER.TICKET_ALREADY_EXISTS";
	String LBL_VOU_PLAYER_ID_IN_MULTIPLE_OVERRIDES	= "LBL.VOUCHER.PLAYER.ID.IN.MULTIPLE.OVERRIDES";

	String VOUCHER_BARCODE_SYSTEM_VALIDATION 	= "VCH.SLOT.BARCODE.VALIDATION";
	String VCH_BARCODE_STANDARD_VALIDATION 		= "VCH.BARCODE.STANDARD.VALIDATION";
	//*****************************************************************//
	String CHOOSE_XML_FILE = "CHOOSE.XML.FILE";
}
