package com.ballydev.sds.voucherui.constants;


public interface IDBPreferenceLabelConstants {

	String LBL_MODULE_NAME="VOUCHER.LBL.MODULE.NAME";

//	Preference Pages Labels
	String PLUGIN_PREFERENCE_GENERAL_DESC = "VOUCHER.PREFERENCE.GENERAL.DESC";
	String PLUGIN_PREFERENCE_GENERAL_TITLE = "VOUCHER.PREFERENCE.GENERAL.TITLE";
	String LBL_SERVER_NAME = "VOUCHER.PREFERENCE.GENERAL.SERVER.NAME";;
	String LBL_SERVER_PORT= "VOUCHER.PREFERENCE.GENERAL.SERVER.PORT";
	String LBL_CASINO_ID = "VOUCHER.PREFERENCE.GENERAL.CASINO.ID";
	String LBL_CASINO_NAME = "VOUCHER.PREFERENCE.GENERAL.CASINO.NAME";
	String LBL_CLIENT_TIME_OUT = "VOUCHER.PREFERENCE.GENERAL.CLIENT.TIME.OUT";
	String LBL_DISPLAY_MODE = "VOUCHER.PREFERENCE.GENERAL.DISPLAY.MODE";
	String LBL_SECONDS = "VOUCHER.PREFERENCE.GENERAL.SECONDS";
	String LBL_BTN_1024_768 = "VOUCHER.PREFERENCE.GENERAL.1024.768";
	String LBL_BTN_800_600 = "VOUCHER.PREFERENCE.GENERAL.800.600";

	String PLUGIN_PREFERENCE_PRINTER_TITLE = "VOUCHER.PREFERENCE.PRINTER.TITLE";

	String PLUGIN_PREFERENCE_LOCATION_DESC = "VOUCHER.PREFERENCE.LOCATION.DESC";
	String PLUGIN_PREFERENCE_LOCATION_TITLE = "VOUCHER.PREFERENCE.LOCATION.TITLE";
	String LBL_BTN_CASHIER = "VOUCHER.PREFERENCE.LOCATION.CASHIER";
	String LBL_BTN_AUDITOR = "VOUCHER.PREFERENCE.LOCATION.AUDITOR";
	String LBL_BTN_ADMIN = "VOUCHER.PREFERENCE.LOCATION.ADMIN";
	String LBL_LOCATION_ID = "VOUCHER.PREFERENCE.LOCATION.LOCATION.ID";
	String LBL_LOCATION_TIME_OUT = "VOUCHER.PREFERENCE.LOCATION.LOCATION.TIME.OUT";
	String LBL_MINS_2_480 = "VOUCHER.PREFERENCE.LOCATION.MINS.2.480";

	String PLUGIN_PREFERENCE_REPORT_DESC = "VOUCHER.PREFERENCE.REPORT.DESC";
	String PLUGIN_PREFERENCE_REPORT_TITLE = "VOUCHER.PREFERENCE.REPORT.TITLE";
	String LBL_CASHIER_REPORT_SETTINGS = "VOUCHER.PREFERENCE.REPORT.CASHIER.REPORT.SETTINGS";
	String LBL_CASHIER_RECONCILIATION_SHOW_BATCH_DETAILS = "VOUCHER.PREFERENCE.REPORT.CASHIER.RECONCILIATION.SHOW.BATCH.DETAILS";
	String LBL_SHOW = "VOUCHER.PREFERENCE.REPORT.SHOW";
	String LBL_BTN_REDEEMED = "VOUCHER.PREFERENCE.REPORT.REDEEMED";
	String LBL_BTN_CREATED = "VOUCHER.PREFERENCE.REPORT.CREATED";
	String LBL_BTN_VOIDED = "VOUCHER.PREFERENCE.REPORT.VOIDED";
	String LBL_BTN_DISPLAY_ALL_BATCHES = "VOUCHER.PREFERENCE.REPORT.DISPLAY.ALL.BATCHES";

	String PLUGIN_PREFERENCE_BARCODE_SCANNER_DESC = "VOUCHER.PREFERENCE.BARCODE.SCANNER.DESC";
	String PLUGIN_PREFERENCE_BARCODE_SCANNER_TITLE = "VOUCHER.PREFERENCE.BARCODE.SCANNER.TITLE";
	String LBL_BTN_BARCODE_SCANNER = "VOUCHER.PREFERENCE.BARCODE.BARCODE.SCANNER";
	String LBL_BTN_TICKET_SCANNER_TEST = "VOUCHER.PREFERENCE.BARCODE.TICKET.SCANNER.TEST";
	String LBL_TEST_STATUS = "VOUCHER.PREFERENCE.BARCODE.TEST.STATUS";
	String LBL_SCANNER_PORT = "VOUCHER.PREFERENCE.BARCODE.SCANNER.PORT";
	String LBL_SCANNER_TYPE = "VOUCHER.PREFERENCE.BARCODE.SCANNER_TYPE";
	String LBL_MANUFACTURER = "VOUCHER.PREFERENCE.BARCODE.MANUFACTURER";
	String LBL_MODEL = "VOUCHER.PREFERENCE.BARCODE.MODEL";
	String LBL_DRIVER = "VOUCHER.PREFERENCE.BARCODE.DRIVER";
	String LBL_TKT_PRINT_TEST_STATUS = "VOUCHER.PREFERENCE.TKT.PRINT.TEST.STATUS";
	String LBL_TKT_PRINT_TEST_TKT_PRINTER = "VOUCHER.PREFERENCE.TKT.PRINT.TKT.PRINTER";

	String PLUGIN_PREFERENCE_TICKET_PRINTER_DESC = "VOUCHER.PREFERENCE.TICKET.PRINTER.DESC";
	String PLUGIN_PREFERENCE_TICKET_PRINTER_TITLE = "VOUCHER.PREFERENCE.TICKET.PRINTER.TITLE";
	String LBL_BTN_TICKET_PRINTING = "VOUCHER.PREFERENCE.TICKET.TICKET.PRINTING";
	String LBL_BTN_PRINT_VOID_TICKET = "VOUCHER.PREFERENCE.TICKET.PRINT.VOID.TICKET";
	String LBL_BTN_MULTIPLE_TICKETS = "VOUCHER.PREFERENCE.TICKET.MULTIPLE.TICKETS";
	String LBL_BTN_SECURE_PRINT = "VOUCHER.PREFERENCE.TICKET.SECURE.PRINT";
	String LBL_MAX_LIMIT = "VOUCHER.PREFERENCE.TICKET.MAX.LIMIT";
	String LBL_PRINTER_PORT = "VOUCHER.PREFERENCE.TICKET.PRINTER.PORT";
	String LBL_PRINTER_TYPE = "VOUCHER.PREFERENCE.TICKET.PRINTER.TYPE";
	String LBL_PASSWORD_PROTECTED_PRINT_TICKET = "VOUCHER.PREFERENCE.TICKET.PASSWORD.PROTECTED.PRINT.TICKET";
	String LBL_BTN_SMALL_SIZE  = "VOUCHER.PREFERENCE.TICKET.PRINTER.SIZE.SMALL";
	String LBL_BTN_NORMAL_SIZE = "VOUCHER.PREFERENCE.TICKET.PRINTER.SIZE.NORMAL";

	String PLUGIN_PREFERENCE_RECEIPT_PRINTER_DESC = "VOUCHER.PREFERENCE.RECEIPT.PRINTER.DESC";
	String PLUGIN_PREFERENCE_RECEIPT_PRINTER_TITLE = "VOUCHER.PREFERENCE.RECEIPT.PRINTER.TITLE";
	String LBL_BTN_RECEIPT_PRINTING = "VOUCHER.PREFERENCE.RECEIPT.RECEIPT.PRINTING";
	String LBL_BTN_RECEIPT_PRINTING_TEST = "VOUCHER.PREFERENCE.RECEIPT.RECEIPT.PRINTING.TEST";

	String PLUGIN_PREFERENCE_CUSTOMER_DISPLAY_DESC = "VOUCHER.PREFERENCE.CUSTOMER.DISPLAY.DESC";
	String PLUGIN_PREFERENCE_CUSTOMER_DISPLAY_TITLE = "VOUCHER.PREFERENCE.CUSTOMER.DISPLAY.TITLE";	
	String LBL_CUST_TEST_MSG = "VOUCHER.PREFERENCE.CUSTOMER.DISPLAY.TEST.MSG";
	String LBL_BTN_CUSTOMER_DISPLAY = "VOUCHER.PREFERENCE.RECEIPT.CUSTOMER.DISPLAY";
	String LBL_BTN_CUSTOMER_DISPLAY_TEST = "VOUCHER.PREFERENCE.CUSTOMER.DISPLAY.CUSTOMER.DISPLAY.TEST";
	String LBL_WELCOME_MESSAGE = "VOUCHER.PREFERENCE.CUSTOMER.DISPLAY.WELCOME.MESSAGE";
	String LBL_DISPLAY_TYPE = "VOUCHER.PREFERENCE.CUSTOMER.DISPLAY.DISPLAY.TYPE";
	String LBL_PORT = "VOUCHER.PREFERENCE.CUSTOMER.DISPLAY.PORT";

	String PLUGIN_PREFERENCE_MULTIAREA_DESC = "VOUCHER.PREFERENCE.MULTIAREA.DESC";
	String PLUGIN_PREFERENCE_MULTIAREA_TITLE = "VOUCHER.PREFERENCE.MULTIAREA.TITLE";
	String LBL_BTN_MULTIAREA = "VOUCHER.PREFERENCE.MULTIAREA.MULTIAREA";
	String LBL_MULTIAREA_ID = "VOUCHER.PREFERENCE.MULTIAREA.MULTIAREA.ID";
	String LBL_SITENAME_ID = "VOUCHER.PREFERENCE.MULTIAREA.SITENAME.ID";
	String LBL_PROPERTY_NAME = "VOUCHER.PREFERENCE.MULTIAREA.PROPERTY.NAME";
	String LBL_PROPERTY_ID = "VOUCHER.PREFERENCE.MULTIAREA.PROPERTY.ID";

	String PLUGIN_PREFERENCE_CHANGE_STC_PWD_DESC = "VOUCHER.PREFERENCE.CHANGE.STC.PWD.DESC";
	String PLUGIN_PREFERENCE_CHANGE_STC_PWD_TITLE = "VOUCHER.PREFERENCE.CHANGE.STC.PWD.TITLE";
	String LBL_ENTER_PWD = "VOUCHER.PREFERENCE.CHANGE.STC.PWD.ENTER.PWD";
	String LBL_ENTER_NEW_PWD = "VOUCHER.PREFERENCE.CHANGE.STC.PWD.ENTER.NEW.PWD";
	String LBL_CONFIRM_PWD = "VOUCHER.PREFERENCE.CHANGE.STC.PWD.CONFIRM.PWD";

	String VOU_INVALID_LOCATION = "VOU.INVALID.LOCATION";

	String VOU_LOC_VALUE_SET="VOU.LOC.VALUE.SET";	

	String VOU_LOC_VALUE_SET_LOGIN="VOU.LOC.VALUE.SET.LOGIN";
	String VOU_PRINT_PREF_NOT_SET="VOU.PRINT.PREF.NOT.SET";
	
	String VOU_PREFERENCES_UPDATED_SUCCESSFULLY = "VOU.PREFERENCES.UPDATED.SUCCESSFULLY";
	String VOU_PREFERENCES_UPDATED_FAILED = "VOU.PREFERENCES.UPDATED.FAILED";
	String VOU_PREFERENCES_SELECT_PRINTER = "VOU.PREFERENCES.SELECT.PRINTER";
	
	String VOU_INVALID_CASHIER_LOCATION = "VOU.INVALID.CASHIER.LOCATION";
	String VOU_CASHIER_LOCATION_NOT_SET = "VOU.CASHIER.LOCATION.NOT.SET";

	String VOU_PREF_TKT_PRINT_COM1 = "VOU.PREF.TKT.PRINT.COM1";
	String VOU_PREF_TKT_PRINT_COM2 = "VOU.PREF.TKT.PRINT.COM2";
	String VOU_PREF_TKT_PRINT_COM3 = "VOU.PREF.TKT.PRINT.COM3";
	String VOU_PREF_TKT_PRINT_COM4 = "VOU.PREF.TKT.PRINT.COM4";
	String VOU_PREF_TKT_PRINT_LPT1 = "VOU.PREF.TKT.PRINT.LPT1";

	String VOU_PREF_TKT_PRINT_TYPE1 = "VOU.PREF.TKT.PRINT.TYPE1";
	String VOU_PREF_TKT_PRINT_TYPE2 = "VOU.PREF.TKT.PRINT.TYPE2";
	String VOU_PREF_TKT_PRINT_TYPE3 = "VOU.PREF.TKT.PRINT.TYPE3";
	String VOU_PREF_TKT_PRINT_TYPE4 = "VOU.PREF.TKT.PRINT.TYPE4";
	String VOU_PREF_TKT_PRINT_TYPE5 = "VOU.PREF.TKT.PRINT.TYPE5";
	String VOU_PREF_TKT_PRINT_TYPE6 = "VOU.PREF.TKT.PRINT.TYPE6";

	String VOU_PREF_DIS_TYPE1 = "VOU.PREF.DIS.TYPE1";
	String LBL_BTN_CENTER_DISP = "VOU.LBL.BTN.CENTER.DISP";
	String LBL_BTN_SCROLL_DISP = "VOU.LBL.BTN.SCROLL.DISP";

	String VOU_DISP_EXPTN_NO_DRIVER ="VOU.DISP.EXPTN.NO.DRIVER";
	String VOU_DISP_EXPTN_NO_CLASS_DEF ="VOU.DISP.EXPTN.NO.CLASS.DEF";
	String VOU_DISP_EXPTN ="VOU.DISP.EXPTN";
	String VOU_DISP_CONNECTION_SUCESS="VOU.DISP.CONNECTION.SUCESS";
	String VOU_DISP_PREF_VALUE_TO_SET="VOU.DISP.PREF.VALUE.TO.SET";
	String VOU_DISP_PREF_LOG_OUT_TO_SET="VOU.DISP.PREF.LOG.OUT.TO.SET";

	String VOU_MULTI_AREA_PREF_VALUE_TO_SET="VOU.MULTI.AREA.PREF.VALUE.TO.SET";

	String VOU_PRINT_SUCCESS = "VOU.PRINT.SUCCESS";
	String TKT_PRINT_EXPTN_NO_DRIVER ="VOU.TKT.PRINT.EXPTN.NO.DRIVER";
	String TKT_PRINT_EXPTN_NO_CLASS_DEF ="VOU.TKT.PRINT.EXPTN.NO.CLASS.DEF";
	String TKT_PRINT_EXPTN ="VOU.TKT.PRINT.EXPTN";
	String TKT_PRINT_CONNECTION_SUCESS="VOU.TKT.PRINT.CONNECTION.SUCESS";
	String VOU_PRINT_PREF_VALUE_TO_SET="VOU.PRINT.PREF.VALUE.TO.SET";
	String RECEIPT_PRINT_CONNECTION_SUCESS="VOU.RECEIPT.PRINT.CONNECTION.SUCESS";

	String REC_PRINT_EXPTN_NO_DRIVER ="VOU.REC.PRINT.EXPTN.NO.DRIVER";
	String REC_PRINT_EXPTN_NO_CLASS_DEF ="VOU.REC.PRINT.EXPTN.NO.CLASS.DEF";
	String REC_PRINT_EXPTN ="VOU.REC.PRINT.EXPTN";
	
	String FRAMEWORK_SCANNER_DUPLO = "FRAMEWORK.SCANNER.DUPLO";
	String FRAMEWORK_SCANNER_CUMMINS = "FRAMEWORK.SCANNER.CUMMINS";
	String FRAMEWORK_SCANNER_MULTISCAN = "FRAMEWORK.SCANNER.MULTISCAN";
	String FRAMEWORK_SCANNER_METROLOGIC = "Metrologic";

	String FRAMEWORK_SCANNER_NO_READ = "FRAMEWORK.SCANNER.NO.READ";

	String FRAMEWORK_SCANNER_MULTI_FEED = "FRAMEWORK.SCANNER.MULTI.FEED";

	String FRAMEWORK_SCANNER_START = "FRAMEWORK.SCANNER.COM.START";

	String FRAMEWORK_SCANNER_STOP = "FRAMEWORK.SCANNER.STOP";

	String FRAMEWORK_SCANNER_CONNECTED = "FRAMEWORK.SCANNER.CONNECTED";

	String FRAMEWORK_SCANNER_NOT_SELECTED = "FRAMEWORK.SCANNER.NOT.SELECTED";
	String VOU_ASSET_EXPTN = "VOU.ASSET.EXPTN";

	String LBL_DISPLAY = "VOUCHER.PREFERENCE.CUSTOMER.DISPLAY";

	String LBL_SIZE = "VOUCHER.PREFERENCE.TKT.PRINT.SIZE";

	String ASSET_FIELD_ONLY_ALPHA_NUMERIC="VOU.ASSET.FIELD.ONLY.ALPHA.NUMERIC";
	String VOUCHER_COLON = "FRAMEWORK.COLON";

	//CASHIER RECEIPT CONSTANTS
	String CASHIER_RECEIPT 					= "VOU.CASHIER.RECEIPT";
	String VALIDATION_NO 					= "VOU.VALIDATION.NO";
	String MAC_NO							= "VOU.MAC.NO";
	String LOCATION_ID 						= "VOU.LOCATION.ID";
	String SYS_GEN_VOU 						= "VOU.SYS.GEN.VOU";
	String OPERATOR_NO 						= "VOU.OPERATOR.NO";
	String ISSUE_DATE 						= "VOU.ISSUE.DATE";
	String PAID_TIME						= "VOU.PAID.TIME";
	String PAID_DATE 						= "VOU.PAID.DATE";
	String INVALID_TKT_AMT 					= "VOUCHER.INVALID.TICKET.AMOUNT";
	String TKT_AMOUNT 						= "VOUCHER.TICKET.AMOUNT";
	
	//PRINT VOUCHER OVERRIDE LOG CONSTANTS
	String OVERRIDE_LOG_CASHIER_RECEIPT 	= "LBL.VOUCHER.OVERRIDE.LOG.RECEIPT";
	String OVERRIDE_LOG_TICKET_NOT_FOUND	= "LBL.VOUCHER.OVERRIDE.LOG.TICKET.NOT.FOUND";
	String OVERRIDE_LOG_CASHIER_NAME		= "LBL.VOUCHER.OVERRIDE.LOG.CASHIER.NAME";
	String OVERRIDE_LOG_APPROVER_NAME		= "LBL.VOUCHER.OVERRIDE.LOG.APPROVER.NAME";
	String OVERRIDE_LOG_APPROVAL_DATE	 	= "LBL.VOUCHER.OVERRIDE.LOG.APPROVAL.DATE";
	String OVERRIDE_LOG_APPROVAL_TIME		= "LBL.VOUCHER.OVERRIDE.LOG.APPROVAL.TIME";
	String OVERRIDE_LOG_BARCODE_NUMBER		= "LBL.VOUCHER.OVERRIDE.LOG.BARCODE.NUMBER";
	String OVERRIDE_LOG_OPERATOR_NO 		= "LBL.VOUCHER.OVERRIDE.LOG.OPERATOR.NO";
	String OVERRIDE_LOG_PAY_THIS_AMOUNT		= "LBL.VOUCHER.OVERRIDE.LOG.PAY.THIS.AMOUNT";
	String OVERRIDE_REDEEMED_SUCCESSFULLY   = "LBL.VOUCHER.OVERRIDE.REDEEMED.SUCCESSFULLY";
	String OVERRIDE_REDEEMED_FAILURE	   	= "LBL.VOUCHER.OVERRIDE.REDEEMED.FAILURE";
	String OVERRIDE_LOG_EXCLUDE_THIS_AMOUNT	= "Excluded Failed Redeem Amount";//"LBL.VOUCHER.OVERRIDE.LOG.EXCLUDE.THIS.AMOUNT";
//	String OVERRIDE_LOG_MAC_NO				= "LBL.VOUCHER.OVERRIDE.LOG.MAC.NO";
//	String OVERRIDE_LOG_LOCATION_ID 		= "LBL.VOUCHER.OVERRIDE.LOG.LOCATION.ID";
//	String OVERRIDE_LOG_TICKET_AMOUNT 		= "LBL.VOUCHER.OVERRIDE.LOG.TICKET.AMOUNT";
//	String OVERRIDE_LOG_BARCODE_STATUS		= "LBL.VOUCHER.OVERRIDE.LOG.BARCODE.STATUS";
}
