package com.ballydev.sds.voucherui.constants;


public interface ITicketConstants {
	
	String  MODULE_NAME="Voucher";

	String CASHIER_RECEIPT ="VOU.CASHIER.RECEIPT";
	String VALIDATION_NO ="VOU.VALIDATION.NO";
	String MAC_NO="VOU.MAC.NO";
	String LOCATION_ID ="VOU.LOCATION.ID";
	String SYS_GEN_VOU ="VOU.SYS.GEN.VOU";
	String OPERATOR_NO ="VOU.OPERATOR.NO";
	String ISSUE_DATE ="VOU.ISSUE.DATE";
	String PAID_TIME= "VOU.PAID.TIME";
	String PAID_DATE ="VOU.PAID.DATE";
	String INVALID_TKT_AMT ="VOUCHER.INVALID.TICKET.AMOUNT";
	String INVALID_AMT = "VOUCHER.INVALID.AMT";
	
	String VOU_PRINTER_CONNECTION_ERROR =  "VOU.PRINTER.CONNECTION.ERROR";
	String VOU_TICKET_PRINTER_CONNECTION_ERROR =  "VOU.TICKET.PRINTER.CONNECTION.ERROR";
	String VOU_REC_PRINTER_CONNECTION_ERROR =  "VOU.REC.PRINTER.CONNECTION.ERROR";
	String VOU_RECEIPT_PRINTER_CONNECTION_ERROR =  "VOU.RECEIPT.PRINTER.CONNECTION.ERROR";
	String TKT_AMOUNT = "VOUCHER.TICKET.AMOUNT";
	
	String VOU_PRINTER_STATUS= "VOU.PRINTER.STATUS";
	String VOU_PRINTER_NOT_ATTACHED = "VOU.PRINTER.NOT.ATTACHED";
	String VOU_PRINTER_READY = "VOU.PRINTER.READY";
	String VOU_PRINTER_NOT_READY = "VOU.PRINTER.NOT.READY";
	String VOU_PRINTER_ERROR_HEAD_IS_UP = "VOU.PRINTER.ERROR.HEAD.IS.UP";
	String VOU_PRINTER_ERROR_PRINTER_OPEN = "VOU.PRINTER.ERROR.PRINTER.OPEN";
	String VOU_PRINTER_ERROR_TICKET_NOT_IN_PRINTER = "VOU.PRINTER.ERROR.TICKET.NOT.IN.PRINTER";
	String VOU_PRINTER_ERROR_TICKET_LOW = "VOU.PRINTER.ERROR.TICKET.LOW";
	String VOU_PRINTER_ERROR_PAPER_JAM = "VOU.PRINTER.ERROR.PAPER.JAM";
	
}
