package com.ballydev.sds.voucherui.constants;

public interface IVoucherPreferenceConstants 
{

	String IS_BARCODE_SCANNER	= "TKTSCANNER_SCAN";
	String SCANNER_PORT			= "TKTSCANNER_PORT";
	String SCANNER_TYPE			= "TKTSCANNER_TYPE";
	String SCANNER_MANUFACTURER	= "TKTSCANNER_MANFT";
	String SCANNER_MODEL		= "TKTSCANNER_MODEL";
	String SCANNER_DRIVER		= "TKTSCANNER_DRIVER";
	String SCANNER_TEST_STATUS 	= "VOUCHER_SCANNER_TEST_STATUS";

	String IS_CUSTOMER_DISPLAY = "VOUCHER_IS_CUST_DISPLAY";
	String IS_DISPLAY_CENTER = "VOUCHER_IS_DISPLAY_CENTER";
	String IS_DISPLAY_SCROLL = "VOUCHER_IS_DISPLAY_SCROLL";
	String CUSTOMER_TEST_STATUS = "VOUCHER_CUST_TEST_STATUS";
	String CUSTOMER_WELCOME_MESSAGE = "VOUCHER_CUST_WELCOME_MESSAGE";
	String CUSTOMER_DISPLAY_TYPE = "VOUCHER_CUST_DISPLAY_TYPE";
	String CUSTOMER_DISPLAY_PORT = "VOUCHER_CUST_DISPLAY_PORT";
	String CUSTOMER_DISPLAY_MANUFACTURER = "VOUCHER_CUST_DISPLAY_MFR";
	String CUSTOMER_DISPLAY_MODEL = "VOUCHER_CUST_DISPLAY_MODEL";
	String CUSTOMER_DISPLAY_DRIVER = "VOUCHER_CUST_DISPLAY_DRIVER";

	String SERVER_NAME = "VOUCHER_SERVER_NAME";
	String SERVER_PORT = "VOUCHER_SERVER_PORT";
	String CASINO_ID = "VOUCHER_CASINO_ID";
	String CASINO_NAME = "VOUCHER_CASINO_NAME";
	String CLIENT_TIME_OUT = "VOUCHER_CLIENT_TIME_OUT";
	String DISPLAY_MODE = "VOUCHER_SERVER_NAME";
	String IS_1024_768 = "DISPLAY_MODE_IS_1024_768";
	String IS_800_600 = "DISPLAY_MODE_IS_800_600";


	String LOCATION_TYPE = "VOUCHER_LOCATION_TYPE";
	String LOCATION_ID = "VOUCHER_LOCATION_ID";
	String LOCATION_TIME_OUT = "VOUCHER_LOCATION_TIME_OUT";
	String LOCATION_IS_ADMIN = "VOUCHER_LOCATION_IS_ADMIN";
	String LOCATION_IS_CASHIER = "VOUCHER_LOCATION_IS_CASHIER";
	String LOCATION_IS_AUDITOR = "VOUCHER_LOCATION_IS_AUDITOR";

	String IS_MULTIAREA = "VOUCHER_IS_MULTIAREA";
	String MULTIAREA_ID = "VOUCHER_MULTIAREA_ID";
	String PROPERTY_NAME = "VOUCHER_PROPERTY_NAME";
	String PROPERTY_ID = "VOUCHER_PROPERTY_ID";
	String SITE_NAME="VOUCHER_SITE_NAME";

	String IS_RECEIPT_PRINTING = "VOUCHER_IS_RECEIPT_PRINTING";
	String RECEIPT_PRINTER_PORT = "VOUCHER_RECEIPT_PRINTER_PORT";
	String RECEIPT_PRINTER_TYPE = "VOUCHER_RECEIPT_PRINTER_TYPE";
	String RECEIPT_PRINTER_MANUFACTURER = "VOUCHER_RECEIPT_PRINTER_MFR";
	String RECEIPT_PRINTER_MODEL = "VOUCHER_RECEIPT_PRINTER_MODEL";
	String RECEIPT_PRINTER_DRIVER = "VOUCHER_RECEIPT_PRINTER_DRIVER";

	String REPORT_IS_REDEEMED = "VOUCHER_REPORT_IS_REDEEMED";
	String REPORT_IS_VOIDED = "VOUCHER_REPORT_IS_VOIDED";
	String REPORT_IS_CREATED = "VOUCHER_REPORT_IS_CREATED";
	String REPORT_IS_DISPLAY_ALL_BATCHES = "VOUCHER_RPT_IS_DSP_ALL_BATCHES";

	String IS_TICKET_PRINTING = "VOUCHER_IS_TKT_PRINTING";
	String IS_MULTIPLE_TICKETS = "VOUCHER_IS_MULTIPLAE_TKTS";
	String IS_SECURE_PRINT = "VOUCHER_IS_SECURE_PRINT";
	String TICKET_PRINTER_PORT = "VOUCHER_TKT_PRINTER_PORT";
	String TICKET_PRINTER_TYPE = "VOUCHER_TKT_PRINTER_TYPE";
	String TICKET_PRINTER_MANUFACTURER = "VOUCHER_TKT_PRINTER_MFR";
	String TICKET_PRINTER_MODEL = "VOUCHER_TKT_PRINTER_MODEL";
	String TICKET_PRINTER_DRIVER = "VOUCHER_TKT_PRINTER_DRIVER";
	String TICKET_PRINTER_NORMAL_SIZE = "VOUCHER_TKT_PRINTER_NORMAL_SIZE";
	String TICKET_PRINTER_SMALL_SIZE = "VOUCHER_TKT_PRINTER_SMALL_SIZE";

	String TICKET_PRINTER_MAX_LIMIT = "VOUCHER_TKT_PRINTER_MAX_LIMIT";

	String STC_PASSWORD = "VOUCHER_STC_PASSWORD";
}
