
-- Backup the DB before adding the field

-- Change context to local SDS DB
USE [SDS_1233]
GO

ALTER TABLE [SLIP].[JACKPOT]
ADD JKPT_INTERCEPT_AMOUNT BIGINT NULL DEFAULT 0;

UPDATE [SLIP].[JACKPOT]
SET JKPT_INTERCEPT_AMOUNT = 0
WHERE JKPT_INTERCEPT_AMOUNT IS NULL;
