/*****************************************************************************
 * $Id: ISiteConfigurationConstants.java,v 1.13, 2010-06-07 12:35:24Z, Ambereen Drewitt$
 * $Date: 6/7/2010 7:35:24 AM$
 * $Log$
 *****************************************************************************
 *           Copyright (c) 2007 Bally Technology  1977 - 2007
 *  All programs and files on this medium are operated under U.S.
 *  patents Nos. 5,429,361 & 5,470,079
 *
 *  All programs and files on this medium are copyrighted works and all rights
 *  are reserved.  Duplication of these in whole or in part is prohibited
 *  without written permission from Bally Gaming Inc.,
 *  Las Vegas, Nevada, U.S.A
 *****************************************************************************/
package com.ballydev.sds.slipsui.constants;

/**
 * Class that contains all the site configuration kays for slips
 * @version $Revision: 14$
 */
public interface ISiteConfigurationConstants {

	//String SHOULD_DMK_FILL_BE_REQUEST="SHOULD.DMK.FILL.BE.F.OR.R";
	
	//String CREATE_DMK_FILL_REQ_MEMO_SLIPS="CREATE.DMK.FILL.REQ.MEMO.SLIPS";
	
	//String CREATE_PENDING_FILL_FOR_DMK_FILL_REQUEST="CREATE.PENDING.FILL.FOR.DMK.FILL.REQ";
	
	//String PREMTIVE_FILL_SUPPORT="PRE.EMPTIVE.FILL.SUPPORT";
	
	String PRINT_VOID_SLIP_FOR_VOID_COMMAND="PRINT.VOID.SLIP.FOR.VOID.COMMAND";
	
	String NO_OF_AUTH_SIGN_FOR_EXCESSIVE_VARIANCES="NO.OF.AUTH.SIGN.FOR.EXCESSIVE.VARIANCES";
	
	//String REQ_AUTH_SIGN_FOR_MANUAL_FILLS="REQ.AUTH.SIGN.FOR.MANUAL.FILLS";
	
	//String REQ_AUTH_SIGN_FOR_PENDING_FILLS="REQ.AUTH.SIGN.FOR.PENDING.FILLS";
	
	String REQ_AUTH_SIGN_FOR_BEEFS="REQ.AUTH.SIGN.FOR.BEEFS";
	
	String REQ_SUPERVISORY_AUTH_FOR_AUTH_EMPLOYEE="REQ.SUPERVISORY.AUTH.FOR.AUTH.EMPLOYEE";// not required--- not sure
	
	String ENABLE_OVERRIDE_AUTH_LEVELS="ENABLE.OVERRIDE.AUTH.LEVELS.SLIP";// not reuqired --- Sure
	
	//String IS_REQUESTER_ALLOWED_TO_PROCESS_PENDING_FILLS="IS.REQUESTOR.ALLOWED.TO.PROCESS.PENDING.FILLS";
	
	//String TREAT_ALL_PENDING_FILLS_AS_PREMTIVE="TREAT.ALL.PENDING.FILLS.AS.PRE.EMPTIVE";
	
	String PROMPT_FOR_SINGLE_SHIFT_OR_DEFAULT="PROMPT.FOR.SHIFT.OR.SINGLE.SHIFT.DEFAULT";
	
	String FILL_BLEED_PROMPT="FILL.BLEED.PROMPT";
	
	String SLIP_FUNCTIONS_REQUIRES_EMPLOYEE_ID = "SLIP.COMMANDS.REQUIRE.EMPLOYEE.ID";
	
	//String BLEED_PASSWORD_ENABLED="SHOULD.BLEED.BE.ALLOWED";
	
	String PROMPT_FOR_SLOT_NO_OR_SLOT_LOCATION ="FILL.BLEED.PROMPT" ;
	
	//String LOOK_UP_FOR_VALID_FILL_AMOUNT="LOOKUP.FOR.VALID.FILL.AMNT";
	
	String ALLOW_WINDOW_NO_ON_BEEF_SLIPS= "ALLOW.WINDOW.ON.BEEF.SLIPS";
	
	//String FILL_PASSWORD_ENABLED="SHOULD.FILL.BE.PASSWORD.CONTROLLED";
	
	String BEEF_PASSWORD_ENABLED="SHOULD.BEEF.BE.PASSWORD.CONTROLLED";
	
	//String DISPLAY_PASSWORD_ENABLED = "SHOULD.DISPLAY.BE.PASSWORD.CONTROLLED";
	
	String REPRINT_BE_ALLOWED="SHOULD.REPRINT.BE.ALLOWED.SLIP";
	
	String VOID_BE_ALLOWED="SHOULD.VOID.BE.ALLOWED";
	
	String REPRINT_PASSWORD_ENABLED="SHOULD.REPRINT.BE.PASSWORD.CONTROLLED";
	
	 String VOID_PASSWORD_ENABLED = "SHOULD.VOID.BE.PASSWORD.CONTROLLED";
	 
	 //String PROMPT_FOR_AREA_FOR_AREA_FILL = "PROMPT.AREA.FOR.ZONE.FILL";
	 
	 //String PROMPT_FOR_SLOT_DENOMINATION_FOR_AREA_FILL = "PROMPT.DEMOM.FOR.ZONE.FILL";
	 
	 //String FILL_BLEED_BEEF_ALLOWED_FOR_OFFLINE_SLOTS = "SHD.FIL.BLED.BE.ALOWD.FOR.OFF.SLOTS";
	 
	 //String FILL_DENOM = "FILL.DENOM";
	 
	 String SLIPS_COMMANDS_REQUIRE_SIGNED_ON_CARDS = "SLIP.COMMANDS.REQUIRE.SIGNED.ON.CARDS";	 
	 
	 String SHOULD_BEEF_BE_ALLOWED = "SHOULD.BEEF.BE.ALLOWED";
	 
	 /** SITE CONFIG KEY FOR -- CURRENCY SYMBOL */
	 
	 String CURRENCY_SYMBOL = "CURRENCY.SYMBOL";
	 
	 //String MAX_BEEF_SLIP_ALLOWED = "MAX.BEEF.SLIP.ALLOWED";
	 
	 /**MULTI AREA PARAMETERS - MULTI AREA SUPPORT FOR FLOOR ROUTING / SLIP COMMANDS */
	 
	 String MULTI_AREA_SUPPORT_FOR_SLIP_COMMANDS = "MULTIAREA.FOR.SLIP.FLOOR.RT";
	 	 
	 //INSTALLED SOFTWARE PARAMETERS - IS CASHIER DESK ENABLED?
	 String IS_CASHIER_DESK_ENABLED = "IS.CASHIER.DESK.ENABLED";
	 
	 //GENERAL PARAMETERS
	 String ALLOW_AUTOMATIC_DEPOSIT_TO_ECASH = "ALLOW.AUTO.DEPOSIT.TO.ECASH.ACCOUNT";
}
