/*****************************************************************************
 * $Id: ISiteConfigConstants.java,v 1.27.1.0.3.0, 2013-10-12 09:01:12Z, SDS12.3.3 Checkin User$
 * $Date: 10/12/2013 4:01:12 AM$
 *****************************************************************************
 *           Copyright (c) 2007 Bally Technology  1977 - 2007
 *  All programs and files on this medium are operated under U.S.
 *  patents Nos. 5,429,361 & 5,470,079
 *
 *  All programs and files on this medium are copyrighted works and all rights
 *  are reserved.  Duplication of these in whole or in part is prohibited
 *  without written permission from Bally Gaming Inc.,
 *  Las Vegas, Nevada, U.S.A
 *****************************************************************************/
package com.ballydev.sds.jackpotui.constants;

/**
 * Interface that contains the Site Configuration Parameter Keys 
 * @version $Revision: 30$
 */
public interface ISiteConfigConstants {

	//String AUTO_AUTH_JACKPOTS="AUTO.AUTH.JPTS.";
	
	String ROUND_JACKPOTS="ROUND.JPTS."; // THIS KEY WILL BE APPENDED WITH THE REST USING THE UTIL CLASS - 	ROUND.JPTS.DENOM.X
	
	String ROUND_PROGRESSIVE_JACKPOTS_TO_NEXT_DOLLAR="RND.PROGRESSIVE.JPTS.TO.NXT.DOLL";
	
	String ROUND_JACKPOTS_TO_NEXT_DOLLAR="RND.JPTS.TO.NXT.DOLL";
	
	String PENDING_JACKPOT_ALLOWED = "SHOULD.JACKPOT.BE.ALLOWED";

	String MANUAL_JACKPOT_ALLOWED = "SHOULD.MANUAL.JACKPOT.BE.ALLOWED";

	String VOID_ALLOWED = "SHOULD.VOID.BE.ALLOWED.JACK";

	String REPRINT_ALLOWED = "SHOULD.REPRINT.BE.ALLOWED";

	String DISPLAY_ALLOWED = "SHOULD.DISPLAY.BE.ALLOWED.JACK";

	String PENDING_JACKPOT_PASSWORD_ENABLED = "SHOULD.PRINT.BE.PASSWORD.CONTROLLED";

	String MANUAL_JACKPOT_PASSWORD_ENABLED = "SHOULD.MANUAL.JACKPOT.BE.PASSWORD.CONTROLLED";

	String VOID_PASSWORD_ENABLED = "SHOULD.VOID.BE.PASSWORD.CONTROLLED.JACK";

	String REPRINT_PASSWORD_ENABLED = "SHOULD.REPRINT.BE.PASSWORD.CONTROLLED.JACK";

	String DISPLAY_PASSWORD_ENABLED = "SHOULD.DISPLAY.BE.PASSWORD.CONTROLLED.JACK";

	String SLIP_FUNCTIONS_REQUIRES_EMPLOYEE_ID = "JPT.COMMANDS.REQUIRE.EMPLOYEE.ID";

	String JACKPOT_FUNCTIONS_REQUIRES_SIGNED_ON_CARDS = "JPT.COMMANDS.REQUIRE.SIGNED.ON.CARDS";

	String PROMPT_FOR_SLOT_NO_OR_SLOT_LOCATION ="JPT.PROMPT" ;

	String PROMPT_FOR_SHIFT_OR_SINGLE_SHIFT = "PROMPT.FOR.SHIFT.OR.SINGLE.SHIFT.DEFAULT.JACK";

	//String SLIP_FUNCTIONS_ALLOWED_FOR_OFFLINE_SLOTS = "SHOULD.JA.BE.ALLOWED.FOR.OFFLINE.SLOTS";

	String TAX_WITHHOLDING_ENABLED = "USE.TAX.WITHHOLDING.ON.JPT.SLIP";

	String STATE_TAX_RATE_FOR_JACKPOT ="STATE.TAX.RATE.FOR.JPT.SLIPS";

	String FEDERAL_TAX_RATE_FOR_JAKCPOT = "FED.TAX.RATE.FOR.JPT.SLIPS";
	
	String MUNICIPAL_TAX_RATE_FOR_JAKCPOT = "MUN.TAX.RATE.FOR.JPT.SLIPS";

	String EXPRESS_JACKPOT_ENABLED = "EXPRESS.JACKPOTS.ENABLED";

	String EXPRESS_JACKPOT_LIMIT = "EXPRESS.JACKPOT.LIMIT";

	String SYSTEM_CLEARS_JACKPOT_WHEN_SLIP_PRINTS = "SLIP.CLRS.JPTS.WHEN.SLIP.PRINTS";

	//String PENDING_JACKPOT_REQUIRES_AUTH_EMPLOYEE_IDS = "SHOULD.JACKPOT.BE.ALLOWED";

	String MANUAL_JACKPOT_REQUIRES_AUTH_EMPLOYEE_IDS = "M.JPT.AMT.REQUIRING.ADDITIONAL.AUTH";

	String PROMPT_FOR_CREDIT_METER_HANDPAY_ON_JP = "PROMPT.FOR.CREDIT.METER.HANDPAY.ON.JPTS";

	String SEPARATE_REPORTING_FOR_PROMOTIONAL_JACKPOT = "SEPARATE.REPORTING.FOR.PROMOTIONAL.JPTS";

	 String NUM_AUTH_SIGNATURES_FOR_EXCESSIVE_VARIANCES = "NO.OF.AUTH.SIGN.FOR.EXCESSIVE.VAR";

	 String JP_DOLLAR_VARIANCE_FOR_ADDITIONAL_AUTHORIZERS = "JPT.DOLL.VAR.FOR.ADDITIONAL.AUTH";

	 String JP_PERCENT_VARIANCE_FOR_ADDITIONAL_AUTHORIZERS = "JPT.PER.VAR.FOR.ADDITIONAL.AUTH";

	 String ENABLE_OVERRIDE_AUTH_LEVELS = "ENABLE.OVERRIDE.AUTH.LEVELS";
	
	 String REQUIRE_SUPERVISORY_AUTHORITY="REQUIRE.SUPERVISORY.AUTH.FOR.AUTHORIZING.EMPLOYEE";
	
	 String JP_REQUIRES_VALID_HPJP_AMOUNT="HPJP.REQUIRES.VALID.HPJP.AMOUNT";
	
	 String ALLOW_PLAYER_NAME_ON_JP_SLIPS="ALLOW.PLAYER.NAME.ON.JPT.SLIPS";
	
	 String ALLOW_WINNING_COMB_ON_JP_SLIPS="ALLOW.WIN.COMB.ON.JPTS.SLIPS";
	
	 String ALLOW_PAYLINE_ON_JP_SLIPS="ALLOW.PAY.LINE.ON.JPTS.SLIPS";
	
	 String ALLOW_COINS_PLAYED_ON_JP_SLIPS="ALLOW.COINS.PLAYED.ON.JPTS.SLIPS";
	
	 String ALLOW_WINDOW_NO_ON_JP_SLIPS="ALLOW.WINDOW.ON.JPTS.SLIPS";
	
	 //String ALLOW_MACHINE_PAY_ON_JP_SLIPS="ALLOW.MACH.PAY.ON.JPTS.SLIPS";
	
	 String ALLOW_PLAYER_CARD_ON_JP_SLIPS="ALLOW.CHANGES.TO.PLAYER.CARD.ON.PR.AND.JA.CMDS";
	
	 String POUCH_PAY_JP_ENABLED="POUCH.PAY.JPTS.ENBLD";

	 String MANUAL_JP_AMOUNT_REQUIRES_ADDITIONAL_AUTHORIZER="M.JPT.AMT.REQUIRING.ADDITIONAL.AUTH";
	 
	 String IS_THE_JACKPOT_INITIATOR_ALLOWED_TO_AUTHORIZE_A_SLIP = "IS.THE.JACKPOT.INITIATOR.ALLOWED.TO.AUTHORIZE.A.SLIP";
	 
	 String PRINT_VOID_SLIP_FOR_VOID_COMMAND = "PRINT.VOID.SLIP.FOR.THE.VOID.COMMAND";	
	 
	 String PERCENT_SLIP_AMT_VARIANCE_QUERY_USER = "PER.OF.SLIP.AMT.VAR.BEFORE.QUERY.USER";
	 
	 String POUCH_PAY_JACKPOT_LIMIT = "POUCH.PAY.JACKPOT.LIMIT";
	 
	 String IS_WINNING_COMB_MANDATORY= "IS.WIN.COMB.MANDATORY";
		
	 String IS_PAYLINE_MANDATORY="IS.PAY.LINE.MANDATORY";
	
	 String IS_COINS_PLAYED_MANDATORY= "IS.COINS.PLAYED.MANDATORY";
	
	 String IS_WINDOW_NO_MANDATORY= "IS.WINDOW.MANDATORY";
	
	 String IS_PLAYER_CARD_MANDATORY= "IS.PLAYER.CARD.MANDATORY";
	 
	 String IS_PLAYER_NAME_MANDATORY ="IS.PLAYER.NAME.MANDATORY";	
	 
	/**CURRENCY GENERAL PARAMETERS - CURRENCY SYMBOL */
	 
	 String CURRENCY_SYMBOL = "CURRENCY.SYMBOL"; 
	 
	 /**MULTI AREA PARAMETERS - MULTI AREA SUPPORT FOR FLOOR ROUTING / SLIP COMMANDS */
	 
	 String MULTI_AREA_SUPPORT_FOR_SLIP_COMMANDS = "MULTIAREA.FOR.SLIP.FLOOR.RT";
	 
	 /** GENERAL PARAMETERS - DENOMINATIONS**/
	 
	 String DENOM_1 = "DENOM.1.VALUE";
	 String DENOM_2 = "DENOM.2.VALUE";
	 String DENOM_3 = "DENOM.3.VALUE";
	 String DENOM_4 = "DENOM.4.VALUE";
	 String DENOM_5 = "DENOM.5.VALUE";
	 String DENOM_6 = "DENOM.6.VALUE";
	 String DENOM_7 = "DENOM.7.VALUE";
	 String DENOM_8 = "DENOM.8.VALUE";
	 String DENOM_9 = "DENOM.9.VALUE";
	 String DENOM_10 = "DENOM.10.VALUE";
	 String DENOM_11 = "DENOM.11.VALUE";
	 String DENOM_12 = "DENOM.12.VALUE";
	 String DENOM_13 = "DENOM.13.VALUE";
	 String DENOM_14 = "DENOM.14.VALUE";
	 String DENOM_15 = "DENOM.15.VALUE";
	 String DENOM_16 = "DENOM.16.VALUE";
	 
	 /* MULTI RANGE JACKPOT SIGNATURE LEVELS */
	 
	 String ENABLE_JACKPOT_MULTI_RANGE_SIGN = "ENABLE.JP.MULTI.RANGE.SIGN"; 
	 
	 String NO_OF_MULTI_RANGE_SIGN_LEVELS = "NO.OF.JP.MULTI.RANGE.SIGN";
	 
	 String MULTI_RANGE_SIGN_1 = "JP.MULTI.RANGE.SIGN.1";   //"5.00"; //"JP.MULTI.RANGE.SIGN.1";
	 String MULTI_RANGE_SIGN_2 = "JP.MULTI.RANGE.SIGN.2";	//"100.00"; //"JP.MULTI.RANGE.SIGN.2";	 
	 String MULTI_RANGE_SIGN_3 = "JP.MULTI.RANGE.SIGN.3";  //"500.00"; //"JP.MULTI.RANGE.SIGN.3";
	 String MULTI_RANGE_SIGN_4 = "JP.MULTI.RANGE.SIGN.4";  //"1000.00"; //"JP.MULTI.RANGE.SIGN.4";
	 String MULTI_RANGE_SIGN_5 = "JP.MULTI.RANGE.SIGN.5";  //"10000"; //"JP.MULTI.RANGE.SIGN.5";	 

	 String PENDING_NON_EXP_JPS_ALWAYS_REQUIRE_EXTRA_AUTHORIZERS ="JP.PEND.NON.EXP.JP.ALWAYS.REQ.EXTRA.AUTH";//Pending Jps Always Require Additional Authorizers
	 
	 //FOR SDS 12.0 and above
	 // SITE CONFIG PARAM FOR PRINTING SLIPS WITH PRINTED STATUS
	 String IS_CASHIER_DESK_ENABLED = "IS.CASHIER.DESK.ENABLED";
	 // Site config parameter for Jackpot amount limit authorization
	 String JACKPOT_AMOUNT_OVERIDE_AUTH_ENABLED = "JACKPOT.AMOUNT.OVERIDE.AUTH.ENABLED";
	 String JACKPOT_AMOUNT_OVERIDE_AUTH_LIMIT = "JACKPOT.AMOUNT.OVERIDE.AUTH.LIMIT";
	 // SITE PARAM FOR AUTO DEPOSIT TO ECASH	 
	 String ALLOW_AUTO_DEPOSIT_TO_ECASH_ACCOUNT = "ALLOW.AUTO.DEPOSIT.TO.ECASH.ACCOUNT";
	 // SITE CONFIG PARAM FOR ENABLING PRINTING JACKPOT SLIP WITH CHECK
	 String ENABLE_CHECK_PRINT_FOR_JACKPOT_SLIP = "ENABLE.CHECK.PRINT.FOR.JACKPOT.SLIP";
	 // SITE CONFIG PARAM FOR GENERATING RANDOM SEQUENCE NUMBER
	 String GENERATE_RANDOM_SEQUENCE_NUMBER = "GENERATE.RANDOM.SEQUENCE.NUMBER";
	 // SITE CONFIG PARAM FOR SHOWING EXPIRY DATE IN THE UI FOR JACKPOT SLIPS
	 String SHOW_EXPIRY_DATE_FOR_PRINTED_SLIP = "SHOW.EXPIRY.DATE.FOR.PRINTED.SLIP";
	 // PROMPTS THE USER WHEN PLAYER IS NOT ACTIVE ON THE SLOT WHEN PROCESSING A MANUAL JP
	 String PROMPT_FOR_ACTIVE_PLAYER_SESSION_ON_JP = "PROMPT.FOR.ACTIVE.PLAYER.SESSION.ON.JPTS"; 
	 
	 
	 //Site Config Params for Jackpot Rounding Options
	 String JACKPOT_ROUNDING_OPTIONS = "ROUND.SLIP.CATEGORY";
	 String JACKPOT_ROUNDING_NEAREST = "ROUND.NEAREST";
	 String JACKPOT_ROUNDING_UP = "ROUND.UP";
	 String JACKPOT_ROUNDING_DOWN = "ROUND.DOWN";
	 
	 // Player Card Length
	 String PLAYER_CARD_NO_LENGTH = "PLAYER.CARD.NO.LENGTH";
	 
	 //Peermont requirement to Auto Void Reprinted Jackpot Slip
	 String ALLOW_AUTO_VOID_ON_REPRINTED_JP = "JP.ALLOW.AUTO.VOID.ON.REPRINTED.JP";
	 
	 //Fix for enhancement CR 99606- The Jackpot Initiator (carded emp) should not be allowed to process the Exp Jp
	 String ALLOW_JACKPOT_INITIATOR_TO_PROCESS_EXP_JP = "JP.ALLOW.INITIATOR.TO.PROCESS.EXP.JP";
}

